### ISSUE TITLE
Server Certificate mismatch

### ISSUE THREAD

**Issue by Pequem** [moonlight-stream/moonlight-qt#195] opened 2019-03-16 16:34 UTC
when i try pair my notebook, the moonlight tell me "server certificate mismatch error 401" on windows 10

**Comment by Pequem** [comment] 2019-03-16 18:38
00:03:38 - Qt Info: Pairing with server generation: 7
00:03:38 - Qt Info: Executing request: "http://192.168.0.12:47989/pair?uniqueid=0123456789ABCDEF&uuid=966dd98c1e1949aa96ccc28ba8700af4&devicename=roth&updateState=1&phrase=getservercert&salt=c0089db665aca6511cf20c16d1d3f68d&clientcert=2d2d2d2d2d424547494e2043455254494649434154452d2d2d2d2d0a4d494943767a43434161656741774942416749424144414e42676b71686b694739773042415155464144416a4d53457748775944565151444442684f566b6c450a53554567523246745a564e30636d56686253424462476c6c626e51774868634e4d546b774d7a45324d5459774d6a51795768634e4d7a6b774d7a45784d5459770a4d6a5179576a416a4d53457748775944565151444442684f566b6c4553554567523246745a564e30636d56686253424462476c6c626e5177676745694d4130470a4353714753496233445145424151554141344942447741776767454b416f49424151444449544e68586c62717a7a6b37525653592f557361645971303068694e0a6748595439495470642b6a5a4f54756161424f73624d733266546c39773939736834776b387155613230663461616972424e595a7547486e62315464595537550a4f686553765a4b3866364644536a6370704c48574b416e4d566d466c554f732b6d503261327a49704855634c34736e31356366535a616f78346d43636b6850610a5162674845716363522f66434346306531505a53514a424556436f557a314e6574794d5154312b6a7658327a614a48616e777379307165744d2b7063383537410a4e75784567522b3352697133447a364f444271575a4e776735332b4749343557464f4564495a2b676c304a7272347a55654a4677466842725a542f314a62535a0a674551657235464d473554486330766136696a37786e615346794744622b48377a416e426670442b77526444656258666e39396a6d74747241674d42414145770a4451594a4b6f5a496876634e415145464251414467674542414b666a7a6f332b6a596f4b2b736e6178334f6b787977572f5757637739654255506a5730795a2f0a437a6f4b4735324b775151456f5a5869597169692f6758742b62504f536b6670425030375739536548565530515a7565712f426f473431645a4550732f7237420a566e484d4a7235436e705130502f7475592f643863516b6d5135363143432b37522f6c53354e71624e566b73584432753443796866555338664c2b65466948610a61626b4839467356485371433248687343575144715877776c3635526d524e6d34763467397546624f5148597576674c2b796d6966566548624d314a626d34620a3972362b4374416c6143574e623468483853355277704778324c637430696f534771642b4d42317a5541624f48376a6c3746362b6245487577384545593158350a6c307263695642496565574f6e576e42466d6e4b2b746276786c4a4a4c557a553841354d68394943323235524f36303d0a2d2d2d2d2d454e442043455254494649434154452d2d2d2d2d0a"
00:03:42 - Qt Info: Executing request: "http://192.168.0.12:47989/pair?uniqueid=0123456789ABCDEF&uuid=357fef00522849afbd5d2f66c06d7810&devicename=roth&updateState=1&clientchallenge=951b53060417815d400e11f8e7cfb9d7"
00:03:42 - Qt Info: Executing request: "http://192.168.0.12:47989/pair?uniqueid=0123456789ABCDEF&uuid=8983fff2dc1747219b76801fcf88536c&devicename=roth&updateState=1&serverchallengeresp=b1804b2052f61a2bcf0187d39728064880795a2d8be64e6b696f5c3dec2fbb80"
00:03:42 - Qt Info: Executing request: "http://192.168.0.12:47989/pair?uniqueid=0123456789ABCDEF&uuid=5bde53d60ebc49e291f6c0c63a25a069&devicename=roth&updateState=1&clientpairingsecret=d684080d10aea4b20a294795642559896776731d8724a105b17ca36f4d02bba50b7a9ad55332ca944dae84725e63c9442556ac5b6e1536922a185ef696131ce52e8d26a35212c1db901ec69ddb643b22a4ab9d2d301d8a40565860a6e442f59bd832477efa3937eae972c925d819adc31ba8945163d21ae5858ec6f6f883e567f5c7562156f79d344d4a5730f5833e174060e9ef760b703a278c1c9c9eae82c13664949116122fc9b297f34cc0d339bb940bac34e7a46f7df9e57d183c614be4a9ca5ff1c37bef664fbaca75a031b6e4867e227255f61344201a37432a57c6a3c70bac1ce60514d561026cef5bcf7deeb9b1c1e782263da4463933d18f24c6e2b883b6e5d1f07dd1cd1340d5d6353696"
00:03:42 - Qt Info: Executing request: "https://192.168.0.12:47984/pair?uniqueid=0123456789ABCDEF&uuid=bc16d7d0685d4019a1fb552ba2ab2691&devicename=roth&updateState=1&phrase=pairchallenge"
00:03:42 - Qt Warning: "pair"  request failed with error  QNetworkReply::SslHandshakeFailedError

**Comment by Pequem** [comment] 2019-03-16 18:38
in my compute, the moonlight can't pair, but in my android device, the moonlight works

**Comment by cgutman** [comment] 2019-03-17 03:41
This is caused by the certificate being dated in the future (as discussed on Discord). Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/37636ef1eb949c611516d0e4c334b808769b9af2

**Closed by cgutman** 2019-03-17 03:41 UTC
