### ISSUE TITLE
HDR Stream washed out, client will not enable HDR

### ISSUE THREAD

**Issue by SgtBlah** [moonlight-stream/moonlight-qt#429] opened 2020-08-21 13:15 UTC
**Describe the bug**
I have the Moonlight windows client installed on a system that supports HDR output running a gtx 1650 super. Whenever I connect to a game (or use the Mass Effect Andromeda workaround) I get dropped from HDR to SDR. The odd part is, my Gamestream source PC is running in HDR (RTX 2060), on an HDR display. This results in the streamed image showing up as very washed out / grey and having my TV switch to SDR. I should be able to see an HDR desktop, or launch supported HDR games without trouble, in theory. Server side logs clearly show gamestream is serving an HDR stream. The client side logs are less verbose and I cannot find any clear indication they are recognizing the stream as HDR.

Both endpoints are fully HDR functioning, both actively in an HDR mode, but when Moonlight initiates a stream, the client drops to SDR (Note I have the experimental HEVC HDR option selected.)

Lastly, when I test Moonlight on my phone, HDR functions just fine. Example, I launch via the Mass Effect work around, then launch Horizon Zero Dawn. Its HDR and looks great on the tiny phone screen. On my Windows client, it is very washed out, grey and the TV is in SDR display mode.

**Steps to reproduce**
No special steps, HDR is not working between my source and windows client

**Affected games**
Windows Desktop
Metro Exodus
Horizon Zero Dawn
Forza Horizon 4
AC: Odyssey
Destiny 2

**Other Moonlight clients**
HDR functions from the same source to an Android Samsung S8 phone without issue.

**Moonlight settings (please complete the following information)**
Yes, resolution set to 4k, bitstream changed to 150mbps and hardware decoder / HEVC HDR enabled.
- Does the problem still occur after reverting settings back to default? Not applicable, issue is related to the HEVC HDR decoder; however adjusting the bitstream downwards has no impact.

**Client PC details (please complete the following information)**
 - OS: Windows 10, 2004
 - Moonlight Version: v2.1.0
 - Nvidia GPU driver: 452.06

**Server PC details (please complete the following information)**
 - OS: Windows 10, 1909 (2004 not yet offered to this system)
 - GeForce Experience version: 3.20.4.14
 - Nvidia GPU driver: 452.06

[Moonlight-1597973937.log](https://github.com/moonlight-stream/moonlight-qt/files/5108978/Moonlight-1597973937.log)

Thanks!

**Comment by cgutman** [comment] 2020-08-29 20:33
It's in the list because the codec list is not platform-specific, and it is marked as "Experimental" but that's probably not a strong enough word. I think it _should_ work on macOS, but I don't have an HDR-capable Mac to test on.

It looks like there's a ticket already for HDR support, so I'll close this as a duplicate of #61

**Closed by cgutman** 2020-08-29 20:33 UTC
