### ISSUE TITLE
RPI 4 running OSMC has washed out colors in HDR

### ISSUE THREAD

**Issue by kurac338** [moonlight-stream/moonlight-qt#974] opened 2023-03-24 16:42 UTC
**Describe the bug**
TV switches to HDR mode, however the colors are noticeably washed out (not as vibrant).

**Other Moonlight clients**
- Android and MacOS behave as expected. 

**Moonlight settings (please complete the following information)**
- 1440p@60Hz@70Mbps
- HDR enabled

**Client PC details (please complete the following information)**
 - OS: OSMC 2023.01-1 (kernel 5.10.78-7-osmc aarch64)
 - Moonlight Version: 4.3.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 22H2 (up-to-date)
 - GeForce Experience version: 3.27.0.112
 - Sunshine: 18.4
 - Nvidia GPU driver: 531.41

**Moonlight Logs (please attach)**
Full log available on [pastebin](https://pastebin.com/74gS9JGi)

**Additional context**
I can see in the logs that Moonlight successfully reports HDR handshake with the TV, however it negotiates a `limited` color range. On first thought it seems to me like the culprit.
``` log
00:06:31 - SDL Info (0): COLOR_RANGE: YCbCr limited range
00:06:31 - SDL Info (0): COLOR_ENCODING: ITU-R BT.2020 YCbCr
```

Native OSMC playback of HDR content works as expected, so it doesn't seem like a Raspbian `config-user.txt` misconfiguration.
Full `config-user.txt` available on [pastebin](https://pastebin.com/4QDavkQb)

**Comment by cgutman** [comment] 2023-03-27 06:28
Limited range is expected for TV content. That is correct.

The issue is that the VC4 driver was configured to only negotiate up to 8 bpc modes. The result is that it would enable HDR but then send 8-bit dithered output which looked wrong.

I added code to set the max BPC property to allow HDMI Deep Color modes in 755c7c989501921d4e095b8c615e61ff136f6a54 and a3d1e9a11732c969383c391926b98f3e94585722. HDR looks correct to me on the Pi now (after calibrating with the HDR Calibration Tool within Windows while streaming). Please test again with the latest code. 

If it still doesn't work, I'll need kernel logs. From a root terminal, run:
```
echo 0xf > /sys/module/drm/parameters/debug
... start streaming and wait for Moonlight to enter HDR mode ...
dmesg
```

There will be a ton of log spam from vc4, but you should see some mode setting lines like:
```
[ 1750.972467] vc4-drm gpu: [drm:vc4_hdmi_encoder_atomic_check [vc4]] Trying with a 12 bpc output
[ 1750.972507] vc4-drm gpu: [drm:vc4_hdmi_encoder_atomic_check [vc4]] Trying with an RGB output
[ 1750.972552] vc4-drm gpu: [drm:vc4_hdmi_sink_supports_format_bpc.isra.33 [vc4]] RGB Format, checking the constraints.
[ 1750.972585] vc4-drm gpu: [drm:vc4_hdmi_sink_supports_format_bpc.isra.33 [vc4]] RGB format supported in that configuration.
[ 1750.972617] vc4-drm gpu: [drm:vc4_hdmi_encoder_atomic_check [vc4]] Failed, Trying with an YUV422 output
[ 1750.972655] vc4-drm gpu: [drm:vc4_hdmi_sink_supports_format_bpc.isra.33 [vc4]] YUV422 format, checking the constraints.
[ 1750.972687] vc4-drm gpu: [drm:vc4_hdmi_sink_supports_format_bpc.isra.33 [vc4]] YUV422 format supported in that configuration.
[ 1750.972719] vc4-drm gpu: [drm:vc4_hdmi_encoder_atomic_check [vc4]] Mode 3840x2160 @ 60Hz: Found configuration: bpc: 12, fmt: YUV 4:2:2, clock: 594000000
[ 1750.972818] vc4-drm gpu: [drm:vc4_atomic_commit_tail [vc4]] Raising the core clock at 534600000 Hz
[ 1750.972911] vc4-drm gpu: [drm:vc4_crtc_atomic_disable [vc4]] Disabling CRTC pixelvalve-2 (96) connected to Encoder TMDS-31 (31)
[ 1750.997847] vc4-drm gpu: [drm:drm_calc_timestamping_constants [drm]] crtc 96: hwmode: htotal 4400, vtotal 2250, vdisplay 2160
[ 1750.998035] vc4-drm gpu: [drm:drm_calc_timestamping_constants [drm]] crtc 96: clock 594000 kHz framedur 16666666 linedur 7407
[ 1750.998139] vc4-drm gpu: [drm:vc4_crtc_atomic_enable [vc4]] Enabling CRTC pixelvalve-2 (96) connected to Encoder TMDS-31 (31)
```

**Comment by kurac338** [comment] 2023-03-27 09:51
Thank you, I will have a look. One question though.
Did the commit go through the CI/CD pipeline? Do you have a link for that commit / build package, or will I need to compile from source?

**Comment by kurac338** [comment] 2023-03-27 13:26
I see that you are building OS specific artifacts per commit on [AppVeyor](https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/46613035/job/hpgbict612eetmp0/artifacts), however I didn't see any non-SteamLink ARM builds.
So, I tried to build my own using the `ubuntu:latest` Docker image on the Pi. I've failed miserably, since I am not really too familiar with all the requirements of this process on ARM.

I would appreciate if you could package this build into a `.deb` so that I may test it and confirm the fix quicker (prior to a full release of a new version).

**Comment by cgutman** [comment] 2023-03-28 05:05
> Did the commit go through the CI/CD pipeline? Do you have a link for that commit / build / artifact package, or will I need to compile from source?

The Pi builds happen under QEMU which takes ages in AppVeyor, so they aren't built normally. They run CI on the [moonlight-packaging](https://github.com/cgutman/moonlight-packaging) repo when I update dependencies.

This build should have the latest fix: https://ci.appveyor.com/project/cgutman/moonlight-packaging/builds/46622475

> @cgutman Would forcing max bpc with modetest have the same effect as those commits? That's what I've been doing and the HDR output is correct.

Yeah, I think that should be equivalent to what Moonlight is doing.

**Comment by kurac338** [comment] 2023-03-28 11:24
I am unable to get the same `dmesg` output.
Here is mine:
``` shell
(as root echo hex flag to debug, and the value changes from "0" to "15")
(starting moonlight HDR stream ...)
osmc@osmc:~$ dmesg | grep vc4-drm > dmesg.txt
```
I have attached the contents of [dmesg.txt](https://pastebin.com/632S5GGU)

Also here are the contents of latest [moonlight-qt.log](https://pastebin.com/36UfxH0a)
This error caught my eye: `00:00:12 - SDL Error (0): drmModeObjectSetProperty(max bpc) failed: 22`

**Comment by kurac338** [comment] 2023-03-29 14:42
I didn't compile that particular version as it would take ages on the PI, however I found a prepackaged version `2.2.0-2 armhf` on the official repositories.

The (massive) output is attached [here](https://pastebin.com/vY4LNRj4).

I can see references to `"max bpc": range [8, 12] = 8` 107 & 126.

**Comment by kurac338** [comment] 2023-04-04 17:19
I've compared the official `4.3.1-3` build (without `max bpc` enforcement) with this `4.3.1.-2` (with `max bpc`).
I can see a definite improvement of HDR color accuracy with `4.3.1.-2` and enforcement of `max bpc`.

I would say it is a subjective 50% improvement over the previous HDR state, but it's still not as accurate to what OSMC displays over RPI4 or what TV native YouTube when looking at the same video frame.

One thing I forgot to mention is that my Samsung (model QE49Q6FN) has 8 bit + **FRC**. Is it possible that FRC is not working, or is this something handled by the display image processing?

**Comment by praxis88** [comment] 2023-06-11 21:47
I've run into this issue as well, but not in OSMC. Mine is just moonlight-qt launched from the cli. 

I seem to get washed out colors no matter the configuration, max bpc 8 or 12, setting it with modetest or not.  The colors are correct on the actual monitor, but the TV says it is entering HDR mode and displays washed out colors. Taking moonlight out of HDR and leaving the source in hdr results in super saturated colors , so something is off 

Version is 4.3.1-3


I did also test with some test media in a kodi GBM build I launch from CLI and it displayed the HDR correctly

**Comment by praxis88** [comment] 2023-06-12 16:56
Sorry for double post but I have gathered some more information on this

max_bpc stays set to 8 until I kill moonlight-qt, set it with modetest -M vc4 -w "32:max bpc:12", and then relaunch moonlight-qt. 

This is the METADATA when it doesnt work properly and looks very washed out. 

...
        38 max bpc:
                flags: range
                values: 8 12
                value: 12
        7 HDR_OUTPUT_METADATA:
                flags: blob
                blobs:

                value:
                        00000000020000000000000000000000
                        00000000000000000000000000000000
```

This is the metadata when it does work properly

```
        38 max bpc:
                flags: range
                values: 8 12
                value: 12
        7 HDR_OUTPUT_METADATA:
                flags: blob
                blobs:

                value:
                        0000000002006b84e33eda2f4e89f31a
                        280a123d4140e80300004c04b4000000
```


I can sometimes get moonlight-qt and even the tty to display in HDR by playing HDR content with kodi and exiting with it still playing. When I do this the metadata value is  0000000002006b84e33eda2f4e89f31a 280a123d4140e80300004c04b4000000 and as soon as I start the moonlight stream it goes to  00000000020000000000000000000000  00000000000000000000000000000000 and has washed out colors


So it's not setting the max_bpc to 12 or the correct value for HDR_OUTPUT_METADATA in  4.3.1-3

**Comment by kurac338** [comment] 2023-06-12 17:26
> Sorry for double post but I have gathered some more information on this
> 
> max_bpc stays set to 8 until I kill moonlight-qt, set it with modetest -M vc4 -w "32:max bpc:12", and then relaunch moonlight-qt.
> 
> This is the METADATA when it doesnt work properly and looks very washed out.
> 
> ```
>         38 max bpc:
>                 flags: range
>                 values: 8 12
>                 value: 12
>         7 HDR_OUTPUT_METADATA:
>                 flags: blob
>                 blobs:
> 
>                 value:
>                         00000000020000000000000000000000
>                         00000000000000000000000000000000
> ```
> 
> This is the metadata when it does work properly
> 
> ```
>         38 max bpc:
>                 flags: range
>                 values: 8 12
>                 value: 12
>         7 HDR_OUTPUT_METADATA:
>                 flags: blob
>                 blobs:
> 
>                 value:
>                         0000000002006b84e33eda2f4e89f31a
>                         280a123d4140e80300004c04b4000000
> ```
> 
> I can sometimes get moonlight-qt and even the tty to display in HDR by playing HDR content with kodi and exiting with it still playing. When I do this the metadata value is 0000000002006b84e33eda2f4e89f31a 280a123d4140e80300004c04b4000000 and as soon as I start the moonlight stream it goes to 00000000020000000000000000000000 00000000000000000000000000000000 and has washed out colors
> 
> So it's not setting the max_bpc to 12 or the correct value for HDR_OUTPUT_METADATA in 4.3.1-3
> 
> The same issue appears to be present across multiple tested HDR screens

Try out this build. It has unreleased changes that should somewhat improve the HDR experience: https://ci.appveyor.com/project/cgutman/moonlight-packaging/builds/46622475

The version is 4.3.1-2 and needs to be installed manually.
For me, it did improve the colours but they are still not 1:1 compared when watching BluRay or YT content.

**Comment by kurac338** [comment] 2023-06-12 17:38
> I'm unsure what to do with that. I see the jobs, and I see the build logs, but I cant seem to find the finished product or intuit what to do with these
> 
> I think it may have been under artifacts but only has a 2 month retention policy?

Thats quite possible. I didn't check the artifact availability. I'll take a look if I have the .deb still saved somewhere.

In any case, those changes will most likely be included in the next version.

**Comment by Bobbar** [comment] 2023-06-13 13:39
@praxis88 

Have you tried forcing the color space with modetest?  Maybe try setting it to Rec.2020 and see if there is a difference.

**Comment by praxis88** [comment] 2023-06-13 22:38
modetest -M vc4 -w "32:Colorspace:9" seems to work properly
For colorspace BT2020_RGB

It's normally just default:0. I have no idea what it is defaulting to

So in my bashrc before I call moonlight-qt i'll run that every time

Thanks bobbar

**Comment by Bobbar** [comment] 2023-06-13 23:05
Right on! 

> So in my bashrc before I call moonlight-qt i'll run that every time

Yep. That's exactly what I'm doing. 

I don't know if it's just my TV, but these extra modetest overrides are the only way I get correct colors in HDR. 

You'll likely have to switch to Rec. 601/709 for SDR stuff, just FYI. Or you'll have the opposite problem. :smile:

For posterity: I'm using a Sony X950H.

**Comment by Bobbar** [comment] 2023-06-13 23:22
Here's the modetest I issue before launching moonlight:

```
modetest -M vc4 -w 32:Colorspace:9 -w 32:"max bpc":10 -w 32:"Broadcast RGB":1
```

Rec.2020, 10-bit colors, Full Range HDMI RGB.

**Comment by praxis88** [comment] 2023-06-13 23:34
I was under the impression you want limited rgb for tvs

**Comment by Bobbar** [comment] 2023-06-13 23:42
> I was under the impression you want limited rgb for tvs

Most of time, yes. But some TVs do support full range. The difference is subtle but noticeable.

![PXL_20230311_031248993~2](https://github.com/moonlight-stream/moonlight-qt/assets/2649098/b11cd6a1-34f3-4d4f-b905-75645b4071e8)

![PXL_20230311_031300515~2](https://github.com/moonlight-stream/moonlight-qt/assets/2649098/22cbea7a-f8fa-4daa-af1e-cda857a47810)

**Comment by praxis88** [comment] 2023-06-14 01:32
> Most of time, yes. But some TVs do support full range. The difference is subtle but noticeable.


Turns out mine supports 0-255 rgb. I just had to set black level to high in the tv and set vc4 broadcast rgb to full. It is subtle but noticable

**Comment by kurac338** [comment] 2023-06-14 09:48
@cgutman as @Bobbar and @praxis88 pointed out, it seems that they have located the missing link to get proper HDR on RPIs.
Is this something that can be implemented in Moonlight?

**Comment by kurac338** [comment] 2023-08-09 13:11
Just to give an update. The issue is still present on the latest (stable) stack.

**Client PC details**
OS: OSMC 2023.07-1 (kernel 5.15.92-1-osmc aarch64)
Moonlight Version: 4.3.1

**Server PC details**
OS: Windows 10 22H2 (up-to-date)
Nvidia GPU driver: 536.67 (GameReady version)
Sunshine: 0.20.0

Also in the meantime I have acquired a new TV. On my system the HDR test results are the same as before; picture not 1:1 when playing exact same content outside of Moonlight vs in Moonlight streams.
If required, I can provide the new EDID output and moonlight log for the new TV set.

@cgutman any updates and/or feedback would be appreciated. 🤞

**Comment by praxis88** [comment] 2023-08-09 14:26
yes, once the max bitdepth is 10 or 12, setting the colorspace manually to BT2020_RGB allows it to work right

**Comment by cgutman** [comment] 2023-08-10 04:08
OK, try with 50255dd896666481f4e08280e8adc6ec0d556a6c. If you can't build from source, I kicked off a build here https://ci.appveyor.com/project/cgutman/moonlight-packaging/builds/47759129 but it will probably take a few hours to finish.

**Comment by kurac338** [comment] 2023-08-10 15:42
I can confirm that this issue is now fixed (using the `50255dd` build).
The image is on par between all of my HDR screens. I am attaching a screenshot of the latest build running on Samsung S90C (acting as a display for RPi 4) and M1 MacBook Air.

![20230810_172921](https://github.com/moonlight-stream/moonlight-qt/assets/36849777/ea5cc1de-5f6e-4a7c-b6c3-e01b9006bc14)

Prior to this build the orange hairs, green leaves and pink tongue were immediately noticeably off-color.

Awesome job everyone on helping diagnose the issue, and a special thanks to Cameron.
Looking forward to future releases :)

**Comment by Bobbar** [comment] 2023-08-10 22:32
@cgutman 

Also confirming. Ran without any prior modetests and colors are correct.

Also works when toggling HDR on/off from the host.

Thank you! :+1:

**Comment by cgutman** [comment] 2023-08-10 23:03
Closing fixed by 50255dd896666481f4e08280e8adc6ec0d556a6c

**Closed by cgutman** 2023-08-10 23:03 UTC

**Comment by Albee-alt** [comment] 2023-09-01 09:36
Hi all, fairly new to the PC side of things, (after being a console gamer for 20+ years) but I’ve also experienced the washed out colours issue. This is probably a stupid question, but how do I use the 50255dd build to resolve this issue?

**Comment by kurac338** [comment] 2023-09-01 09:39
It depends on what is your client device...
But take a look at this link https://ci.appveyor.com/project/cgutman/moonlight-packaging/builds/47759129 , it still hosts prebuilt artifacts you can try, including .deb packages for Raspberry Pis.
