### ISSUE TITLE
Several problems after updating Moonlight to 3.1.1 

### ISSUE THREAD

**Issue by Dantido2** [moonlight-stream/moonlight-qt#582] opened 2021-04-26 20:35 UTC
**Describe the bug**
After I've updated my Moonlight to 3.1.1, I've been facing a lot of problems. These are the ones I've been noticing the most :
- A noticeable audio delay. It's not terrible, but annoying. It persists even after disabling MSI Afterburner/RTSS and restarting the stream several times.
- Terrible stream cuts when at higher than 40mbps bitrate, even though my internet is supposedly a stable 47-48mbps upload from the numerous tests I did.
- Error 552, which pops sometimes when trying to connect to the host PC. 
- Error 10060, which pops sometimes when trying to connect to the host PC in a similar fashion to the Error 552. Both errors ask me to check the internet ports, but I've used the Internet Streaming Tool to do all of this and it said everything was okay.

**Screenshots**
If necessary, I can record videos, but I currently have none.

**Affected games**
I've tried this with the GameStreamFixMouse app and nothing else.
The game I've "benchmarked" on the log was Project Brutality 3.0, an overhaul of GZDoom perfect for video stress tests due to the amount of particles. This game was not launched directly from the Moonlight app.

**Other Moonlight clients**
I've never tried this on iOS or Android.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes, the V-Sync has been turned off and the bitrate has been set to 47. The issues persist unless I set the bitrate to 40 or lower. I've also set the resolution and refresh rate to 1680x1050 and 60hz respectively.
- Does the problem still occur after reverting settings back to default? No, as the bitrate is reduced.

**Client PC details (please complete the following information)**
 - OS: Windows 7
 - Moonlight Version:  311
 - GPU: [e.g. Intel HD Graphics 520]

**Server PC details (please complete the following information)**
 - OS: Windows 191
 - GeForce Experience version: Latest (3.22, the one that caused problems for versions of Moonlight equal or older than 3.1.0)
 - Nvidia GPU driver:  Latest.
 - Antivirus and firewall software: Windows Defender & Windows Firewall.
 
**Moonlight Logs (please attach)**
[Moonlight-1619454852.log](https://github.com/moonlight-stream/moonlight-qt/files/6379992/Moonlight-1619454852.log)
Here's a list of things I did today that should be reflected on the log :
-Tried launching the Moonlight app as usual after updating.
-After connecting for the first time, I started having connection issues.
-After a while, the stream completely froze, forcing me to quit the stream.
-Tried restarting the stream, but I'm unable to reconnect again.
-Tried lowering the bitrate to tiny amounts to make it work. Still had a bit of connection issues.
-Tested my internet multiple times, and it was a consistent 45-47mbps all the time.
-Played with the bitrate a  bit to see if I could fix it, but it was of no use.
-Once I managed to make it work by setting the bitrate to 40mbps, it went fairly well. However, now that it went well visually, I started to notice the audio delay.
-Tried closing MSI Afterburner and rebooting the PC. Audio delay was still there. 
-Decided to finish the day by playing a bit of Project Brutality to "benchmark" Moonlight, using HWInfo to measure temps and all that instead. The stream went badly only when the game dropped below 60FPS.
-Lowered the bitrate again (35), and the game was now running smoothly, although the audio delay was still very noticeable.
-The game crashed (as it's usual with PB, since it's a mod), and the stream froze completely. 
-Closed the stream again, and wrapped things up to start writing this issue in GitHub!

**Additional context**
I'm going to rip my hair out because of internet issues, but I'll put some context :
-My internet provider sucks, but they're very helpful, at least. They recently replaced my router since the one I had before had issues with keeping the upload speed stable. I've yet to test this router well, but this might be of interest.

**Comment by cgutman** [comment] 2021-04-26 22:34
Your video packet loss is related to the workaround in v3.1.1 to avoid receiving multi-FEC frames from GeForce Experience 3.22. You've got a little packet loss on your connection which would normally be covered by the extra FEC data, but we have to disable FEC for bitrates and resolutions that could trigger a multi-FEC frame in the following code: https://github.com/moonlight-stream/moonlight-common-c/blob/ca4019c09f0b8a942e3b9e5a9023e9bfe012e383/src/SdpGenerator.c#L172-L178

The audio delay problem is not related, and there were no changes in that area in v3.1.1. If the delay is indeed new, it wasn't introduced by Moonlight v3.1.1. The cause lies elsewhere.

The other connection errors just look like a flaky network connection (which is further supported by the packet loss necessitating FEC recoveries).

**Comment by cgutman** [comment] 2021-04-27 03:56
I managed to reverse engineer how multi-FEC frames work with GFE 3.22 and implemented support in Moonlight. Please try out the latest build here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38886929/job/l6o9k9i5u7of0gf3/artifacts

It should also contain a fix for the audio latency, so let me know how that is too.

**Comment by Dantido2** [comment] 2021-04-27 14:35
Thank you so much, cgut! I'm going to try it right now!

**Comment by Dantido2** [comment] 2021-04-27 14:51
Alright, I've just tried it out, and I can definitely say the audio delay is much less now, but it's still noticeable. I'll try it out more, with and without MSI Afterburner, and see what goes.
Again, thank you so much, cgut!

**Comment by Dantido2** [comment] 2021-04-27 16:43
After trying it for a while, although Moonlight does not cut short every now and then anymore, it does drop frames a lot. Curiously, it only happens when I am inside games, for some ungodly reason. 
This would all point out that I have slow internet and that I should just reduce the bitrate, but here's the thing : I've tested my internet a thousand times, and the upload speed is always above 45mbps. Yeah, my mind is also blown.
I'll send the log of my playthrough with this build right now...

**Comment by Dantido2** [comment] 2021-04-27 16:47
[Moonlight_Game_Streaming_Client_20210427163346_000_Moonlight_x64.log](https://github.com/moonlight-stream/moonlight-qt/files/6386220/Moonlight_Game_Streaming_Client_20210427163346_000_Moonlight_x64.log)
[Moonlight_Game_Streaming_Client_20210427163346.log](https://github.com/moonlight-stream/moonlight-qt/files/6386222/Moonlight_Game_Streaming_Client_20210427163346.log)
Apparently I have two, oh well.

**Comment by cgutman** [comment] 2021-04-27 16:49
Oh, those are installer logs. The Moonlight logs for a portable version are stored in the same folder as Moonlight.exe.

Can you get those logs?

**Comment by Dantido2** [comment] 2021-04-27 16:54
[Moonlight-1619534183.log](https://github.com/moonlight-stream/moonlight-qt/files/6386257/Moonlight-1619534183.log)
Got it, here they are.

**Comment by cgutman** [comment] 2021-05-01 01:22
As we discussed on Discord, it looks like Moonlight is working well now (FEC recovery is working at 4K) and there's something else going on with your connection that's causing packet loss at relatively low bitrates. The packet loss rates exceed those that even the maximum supported GameStream FEC level could recover.

Since the Moonlight bug is addressed, I'm closing this now as fixed by e081401c2d6887ea9feb85785dd27c7595510829

**Closed by cgutman** 2021-05-01 01:22 UTC
