### ISSUE TITLE
Moonlight on SteamLink displays second monitor

### ISSUE THREAD

**Issue by roughnecks** [moonlight-stream/moonlight-qt#729] opened 2022-02-04 23:37 UTC
**Describe the bug**
I've got two monitors on my PC but Windows sets them in the wrong order.. 1 on the right and 2 on the left, so I do arrange them manually, setting 2 as my primary monitor: https://i.imgur.com/t2s7KJD.jpeg

When booting up a game on Moonlight, it displays my second monitor instead of the primary and I can't see/control the game.

**Affected games**
I've only tried with Euro Truck Simulator 2

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?

No.

**Info**
 - OS: Windows 10 21H2
 - Moonlight for SteamLink 3.2.0
 - GPU: GTX 1660 Gaming 6GB
 - GeForce Experience version 3.24.0.126
 - Nvidia GPU driver: Studio 511.65
 - Windows Defender and Windows Firewall

I would like to add that I reset my PC a couple days ago and last time I played (before resetting) everything worked just fine.

Thanks

**Comment by cgutman** [comment] 2022-02-05 23:19
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/22

**Closed by cgutman** 2022-02-05 23:19 UTC
