### ISSUE TITLE
MacBook Pro Touch Bar support

### ISSUE THREAD

**Issue by Anatharias** [moonlight-stream/moonlight-qt#406] opened 2020-06-06 02:41 UTC
**Is your feature request related to a problem? Please describe.**
Difficult to press F keys while gaming on a MacBook Pro with TouchBar (tiny oled display that replaces Function F1-F12 keys on some high end 2016-current MacBook Pros).

**Describe the solution you'd like**
Moonlight to force the Touchbar display to be in "F Keys mode"

**Describe alternatives you've considered**
Pressing fn key is cumbersome and sometimes doesn't send the propre key to the host

**Additional context**
default TouchBar behaviour is control strip, pressing the fn key brings the display of F1-F12 keys. Doing so messes up the hotkeys
You can setup the system settings to only display the F keys, but they are 100% useless in the Mac environment.

**Comment by cgutman** [comment] 2020-06-07 18:52
Duplicate of #296

**Closed by cgutman** 2020-06-07 18:52 UTC

**Comment by OskarZyg** [comment] 2024-12-27 23:42
For those who are still looking for this feature, you can fake it by heading to Settings -> Accessibility -> Keyboard -> Keyboard Shortcuts -> Function Keys and then adding Moonlight to the application list.
![image](https://github.com/user-attachments/assets/c326df78-f6ab-43f5-a24f-9c3e76cd636d)
Be aware that function keys will still show on the device & application selection screen which can be annoying but I think it's an okay compromise.
