### ISSUE TITLE
Pc stream.ok, but games are unplayable

### ISSUE THREAD

**Issue by nattyduber** [moonlight-stream/moonlight-qt#842] opened 2022-08-09 19:57 UTC
Hi

Before i used Moonlight streaming on a desktop with i7 6700+gtx1080 and all work fine
Now im on a desktop Lenovo légion 5 with ryzen 5 and rtx 3070
And i have paired m'y laptop on Android TV or m'y phone
Internet hosting tool Saïd that all are ok

But when i want to connect to m'y pc .. rtsp etc load , no problème .. but when i want to launch a game there are a message ''poor internet connection etc''

I use fiber connections in wifi.. 2gb connections..
With or without allm or hardware accelation.. its the same problèm.. they Say ''poor connections please have a better connection'' ..

How to solve it!?
.
On a Galaxy z fold 3 or NVIDIA Shield TV 2019

Thanks

**Comment by cgutman** [comment] 2022-08-10 00:06
Duplicate of https://github.com/moonlight-stream/moonlight-android/issues/1085

**Closed by cgutman** 2022-08-10 00:06 UTC
