### ISSUE TITLE
(macOS) Mouse Input is slightly inaccurate

### ISSUE THREAD

**Issue by Tsubajashi** [moonlight-stream/moonlight-qt#608] opened 2021-06-06 23:13 UTC
**Describe the bug**
mouse on host is shifted a bit top-left from the actual mouse position

**Steps to reproduce**
Use macOS 11.4 on M1 MacBook Air - not sure if anyone else is affected, was only able to test it on that specific device

**Screenshots**
A Video will be sent shortly since you can see the actual mouse position when you resize a window

**Affected games**
Any game, and Remote Desktop.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?
Sadly not sure... didn't test those devices.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- Depending on how its seen, 1080p60.
- Does the problem still occur after reverting settings back to default?
- Doesn't seem to have an affect on it.

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - macOS 11.4 on MacBook Air M1 2020
 - Moonlight Version: [e.g. v0.9.0]
 - v3.1.3
 - GPU: [e.g. Intel HD Graphics 520]
 - Apple M1

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Windows 10 2104
 - GeForce Experience version: [e.g. 3.16.0.140]
 - 3.22.0.32
 - Nvidia GPU driver: [e.g. 417.35]
 - 466.47
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]
 - Windows Defender and Windows Firewall.

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`
- [Moonlight-1623020826.log](https://github.com/moonlight-stream/moonlight-qt/files/6605111/Moonlight-1623020826.log)

**Additional context**
If anything else is needed, I will give it to you for sure. not sure what else I could provide.

**Comment by Tsubajashi** [comment] 2021-06-06 23:20
https://user-images.githubusercontent.com/21346945/120943328-88a6fc00-c72e-11eb-8476-640c9ea96fcd.mp4

here is an example in video form.

**Comment by cgutman** [comment] 2021-06-07 00:37
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/10

**Closed by cgutman** 2021-06-07 00:37 UTC
