### ISSUE TITLE
Force Resolution for Moonlight-qt GUI

### ISSUE THREAD

**Issue by SchwingMC** [moonlight-stream/moonlight-qt#645] opened 2021-09-04 19:12 UTC
**Is your feature request related to a problem? Please describe.**
I'm using Moonlight-qt on a Raspberry Pi 4 with a LibreElec-RR build [(here](https://forum.libreelec.tv/thread/23644-libreelec-rr-10-x-brave-spotify-moonlight-emulationstation-retroarch-pegasus/) and [here](https://github.com/SupervisedThinking/LibreELEC-RR)) on a 4k TV. For performance reasons I want to run kodi at  1080@60, which works perfectly fine, however, if I run Moonlight the resolution switches to 4k@30. If I opt for 1080@60 in the Moonlight  settings, the stream is incoming at 1080 with 60 fps, but the TV resolution is still at 4k@30, which causes tearing on the screen. 
![PXL_20210904_185203065 MP](https://user-images.githubusercontent.com/85257001/132105414-47c0c6ab-5f46-425b-a0c8-9c6541895fba.jpg)
![PXL_20210904_185644550 MP](https://user-images.githubusercontent.com/85257001/132105434-705e8144-6011-4c3c-a1c9-fda56e8523ea.jpg)
 

**Describe the solution you'd like**
An option to force the Moonlight gui to run at a specific resolution would be nice. 

**Describe alternatives you've considered**
I already tried to force this on libreelec side by adding `video=HDMI-A-1:1920x1080@60D` and `drm.edid_firmware=HDMI-A-1:edid/edid-HDMI-A-1.bin video=HDMI-A-1:1920x1080D` to cmdline.txt, but this doesn't work. 
**Additional context**

**Comment by LATINO-BICEPS** [comment] 2021-11-25 14:10
Hey I'm struggling with the same issue as you with the GUI defaulting to the highest resolution the TV supports. I'm wondering if you had any workarounds/fixes since then?

**Comment by SchwingMC** [comment] 2021-11-25 14:30
Hi, yes I have a workaround for libreelec. 
But I must inform you that this kills CEC functions (you won't be able to use your TV remote to control libreelec) and HDMI audio. 
If you want to try it anyway, add 
`drm.edid_firmware=HDMI-A-1:edid/1920x1080.bin video=HDMI-A-1:D` to cmdline.txt. Be sure to add it at the end of cmdline.txt, make NO extra line. 
Greetings

**Comment by LATINO-BICEPS** [comment] 2021-11-25 15:08
No HDMI audio is such a dealbreaker for me. Nice that you found a solution for your use case regardless.

On a related note, I was digging into the [QT docs](https://doc.qt.io/qt-5/embedded-linux.html) and got the GUI to run at 1080p60 by running `QT_QPA_PLATFORM=linuxfb:size=1920x1080 moonlight-qt`. Slight problem, I have awful lines zapping across the screen but it is not too bad.

**Comment by xanarin** [comment] 2021-12-06 01:47
I ran into this same issue after getting a new TV on Black Friday. I was seeing stutters in my 1080p60 stream because the display was actually running at 4K30. I was able to work around it by adding the following lines to my `/boot/config.txt`:
```
# Force HDMI to do 1080p60 (even though the TV supports higher)
hdmi_ignore_edid=0xa5000080
hdmi_group=2
hdmi_mode=69
```
The first line tells the Pi to ignore the resolutions that the TV reports (over EDID) that it supports. This causes my Pi 4 to only use the resolution/mode that I set in the last two lines: `1080p @ 60Hz`. More details on these options can be found in the [elinux RPiconfig documentation](https://elinux.org/RPiconfig#Video).

Audio over HDMI still works, but I'm unsure of whether CEC works (because I don't have a great way to test it). The one drawback is that it causes text elements in the Moonlight GUI to become much larger than they should, however once streaming starts everything works very smoothly.

![computers](https://user-images.githubusercontent.com/5807289/144774378-ccf92b7e-57ef-4322-97b8-f202a5bb3d61.png)
![settings](https://user-images.githubusercontent.com/5807289/144774386-1f686f15-9155-42ab-a80c-19295085b6d7.png)
_Screenshots taken with [raspi2png](https://github.com/AndrewFromMelbourne/raspi2png)_

**Comment by awoelfl** [comment] 2022-01-22 19:12
My setup:
- 4k@30 TV (Samsung 2016 Model)
- Raspberry PI 4
- LibreELEC 10
- Moonlight QT 3.2.0 (compiled via Docker, see https://github.com/veldenb/plugin.program.moonlight-qt)
- HVEC enabled by `dtoverlay=rpivid-v4l2`

I got it working by combining @LATINO-BICEPS and @SchwingMC approaches. In a nutshell, I configured the "shell-resolution" in `cmdline.txt` and export `QT_QPA_PLATFORM`  before launching moonlight.

Detailed steps:
- Make `cmdline.txt` editable by executing `mount -o rw,remount /flash`
- Execute `nano /flash/cmdline.txt` and append `video=HDMI-A-1:1920x1080M-32@60:mD` to the kernel line (i.e., the first line) (see https://www.kernel.org/doc/Documentation/fb/modedb.txt)
- Execute `nano /storage/.kodi/addons/plugin.program.moonlight-qt/resources/bin/bootstrap_moonlight-qt.sh` and add `export QT_QPA_PLATFORM=linuxfb:size=1920x1080` as second line after the shebang `!#/bin/bash`

This way i got CEC, audio, and 60fps in moonlight working. Note that the change in `cmdline.txt` does not force the resolution to 1080p, Kodi is still able to switch to 2160p when playing 4k content.

**Comment by SchwingMC** [comment] 2022-01-29 14:18
There seems to be an update on the Moonlight side of things. Due to the build I'm using I can't edit moonlight-qt.sh (I'm using LibreELEC-RR from SupervisedThinking). So I created a new  image from recent source. Only cmdline.txt was edited in the way @awoelfl is suggesting. Now the Moonlight user interface is in 4k, but the actual streaming content is displayed in 1080*60 if this is selected in the moonlight options. Also CEC and HDMI audio are working.

**Comment by cgutman** [comment] 2022-01-29 19:49
Yep, I enabled switching into 1080p60 here: e56bb6785f7a9e1dbbfad4764b0b631e64b0b471

So that's fixed in Moonlight v3.2.0.

**Comment by arnerak** [comment] 2022-04-24 11:32
> There seems to be an update on the Moonlight side of things. Due to the build I'm using I can't edit moonlight-qt.sh (I'm using LibreELEC-RR from SupervisedThinking). So I created a new image from recent source. Only cmdline.txt was edited in the way @awoelfl is suggesting. Now the Moonlight user interface is in 4k, but the actual streaming content is displayed in 1080*60 if this is selected in the moonlight options. Also CEC and HDMI audio are working.

Unfortunately this is not the case for me. The `moonlight-qt.log` file suggests the correct resolution was picked but the TV still reports 4K@30. 
`00:00:15 - SDL Info (0): Chosen best display mode: 1920x1080x60`
Adding the QT environment variable that @LATINO-BICEPS was suggesting makes moonlight-qt crash on launch. All I can see regarding this in the log is `floating point exception`. Without the change to `/flash/cmdline.txt` moonlight-qt launches, but only moonlight-qt's render size is changed, not the screen resolution:
![grafik](https://user-images.githubusercontent.com/29173710/164974158-a8a9a3bd-b701-4528-afaa-928ff7b00ec2.png)
The suggestion from @xanarin doesn't work for me either, I can still see all TV resolutions inside LibreElec's settings and moonlight-qt will launch in 4K.

**Comment by SchwingMC** [comment] 2022-04-24 12:18
You have to start an app, for example the Desktop or the game you want to play. It should then be started in 1080p.

**Comment by awoelfl** [comment] 2022-04-28 06:14
hm i can confirm the issue described by @arnerak. Screen resolution stays at 4k with the new 4.0.0 version

**Comment by arnerak** [comment] 2022-05-11 10:02
To make it work for 4.0.0 I had to
- append `video=HDMI-A-1:1920x1080M-32@60:mD` to `/flash/cmdline.txt`
- add `export QT_QPA_PLATFORM=linuxfb:size=1920x1080` to `bootstrap_moonlight-qt.sh`
- change `QT_SCALE_FACTOR=0.93` to `QT_SCALE_FACTOR=1.0` in `bootstrap_moonlight-qt.sh` for moonlight-qt to not crash on launch (not a real fix, the gui looks awful now)

**Comment by cgutman** [comment] 2022-05-12 00:36
Sounds like a possible SDL bug, since the behavior shouldn't have changed between v3.2.0 and v4.0.0. Can you post logs from moonlight after streaming?

**Comment by awoelfl** [comment] 2022-05-12 04:23
@arnerak thank you for sharing, setting the scale to 1 works for me as well
@cgutman please find attached logs for:

- moonlight-scale-1-1080.log: with `QT_QPA_PLATFORM=linuxfb:size=1920x1080 ` and `QT_SCALE_FACTOR=1.0`
- moonlight-scale-0.93-1080.log: with `QT_QPA_PLATFORM=linuxfb:size=1920x1080 ` and `QT_SCALE_FACTOR=0.93`(crashes)
- moonlight-scale-0.93-4k.log: with `QT_SCALE_FACTOR=0.93`

However, the scaling factor is set by a kodi addon (https://github.com/veldenb/plugin.program.moonlight-qt) in my case. Git blame revealed that the scaling factor was added in a rather recent commit (https://github.com/veldenb/plugin.program.moonlight-qt/commit/d28988edd0d1b1c31e2bb9cc1149b8f4edcf994f). My hypothesis is that the feature broke not due to the update from moonlight-qt but due to an update of the kodi addon. So nothing you guys need to tackle?

[moonlight-scale0.93-4k.log](https://github.com/moonlight-stream/moonlight-qt/files/8674912/moonlight-scale0.93-4k.log)
[moonlight-scale0.93-1080.log](https://github.com/moonlight-stream/moonlight-qt/files/8674913/moonlight-scale0.93-1080.log)
[moonlight-scale1-1080.log](https://github.com/moonlight-stream/moonlight-qt/files/8674914/moonlight-scale1-1080.log)
.

**Comment by cgutman** [comment] 2022-05-14 21:56
Yeah it looks like Moonlight is deciding to use 1080p 60 Hz while streaming, so it seems to be choosing the intended resolution and the bug is probably elsewhere.

```
00:00:13 - SDL Info (0): Detected display mode: 4096x2160x30
00:00:13 - SDL Info (0): Detected display mode: 4096x2160x25
00:00:13 - SDL Info (0): Detected display mode: 4096x2160x24
00:00:13 - SDL Info (0): Detected display mode: 3840x2160x30
00:00:13 - SDL Info (0): Detected display mode: 3840x2160x25
00:00:13 - SDL Info (0): Detected display mode: 3840x2160x24
00:00:13 - SDL Info (0): Detected display mode: 1920x1080x60
00:00:13 - SDL Info (0): Detected display mode: 1920x1080x50
00:00:13 - SDL Info (0): Detected display mode: 1920x1080x30
00:00:13 - SDL Info (0): Detected display mode: 1920x1080x25
00:00:13 - SDL Info (0): Detected display mode: 1920x1080x24
00:00:13 - SDL Info (0): Detected display mode: 1680x1050x60
00:00:13 - SDL Info (0): Detected display mode: 1600x900x60
00:00:13 - SDL Info (0): Detected display mode: 1440x900x60
00:00:13 - SDL Info (0): Detected display mode: 1280x1024x75
00:00:13 - SDL Info (0): Detected display mode: 1280x1024x60
00:00:13 - SDL Info (0): Detected display mode: 1280x800x60
00:00:13 - SDL Info (0): Detected display mode: 1280x720x60
00:00:13 - SDL Info (0): Detected display mode: 1280x720x50
00:00:13 - SDL Info (0): Detected display mode: 1152x864x75
00:00:13 - SDL Info (0): Detected display mode: 1024x768x75
00:00:13 - SDL Info (0): Detected display mode: 1024x768x70
00:00:13 - SDL Info (0): Detected display mode: 1024x768x60
00:00:13 - SDL Info (0): Detected display mode: 832x624x75
00:00:13 - SDL Info (0): Detected display mode: 800x600x75
00:00:13 - SDL Info (0): Detected display mode: 800x600x72
00:00:13 - SDL Info (0): Detected display mode: 800x600x60
00:00:13 - SDL Info (0): Detected display mode: 720x576x50
00:00:13 - SDL Info (0): Detected display mode: 720x480x60
00:00:13 - SDL Info (0): Detected display mode: 720x400x70
00:00:13 - SDL Info (0): Detected display mode: 640x480x75
00:00:13 - SDL Info (0): Detected display mode: 640x480x73
00:00:13 - SDL Info (0): Detected display mode: 640x480x67
00:00:13 - SDL Info (0): Detected display mode: 640x480x60
00:00:13 - SDL Info (0): Chosen best display mode: 1920x1080x60
```

**Comment by awoelfl** [comment] 2022-05-19 06:05
FYI: veldenb provided a fix for the plugin.program.moonlight-qt addod. See:  https://github.com/veldenb/plugin.program.moonlight-qt/issues/19

@cgutman i think we can close this one

**Comment by veldenb** [comment] 2022-05-19 21:52
The fix is a bit hacky using the QT_QPA_EGLFS_KMS_CONFIG env var but it seems to work well.

**Closed** 2022-05-20 01:21 UTC

**Comment by cgutman** [comment] 2022-05-25 01:13
It turned out that there was indeed a bug in Moonlight here when streaming H.264 due to some unexpected behavior in SDL.

In KMSDRM mode, SDL will only apply the selected display mode on the next buffer swap. Since the MMAL renderer doesn't use SDL for rendering, the modeset never applies, even though SDL claims the current display mode is the one selected by Moonlight. That bug is fixed in b9c73df488f279fd1d548933114326155fd622dc for v4.1.0

**Comment by veldenb** [comment] 2022-05-28 14:35
@cgutman does this also cover H.265 (HEVC)?

**Comment by cgutman** [comment] 2022-05-29 02:55
Nope, it looks like HEVC is affected if using HDR or if `GL_OES_EGL_image` is unsupported (which doesn't seem to be the case normally, but happens in your logs). That is fixed in 9daf7b5a362f2aff90e61ad16f8390ec637e5f5b and will be deployed in v4.1.0-2 versions of the RPi and RPi64 packages.

**Comment by veldenb** [comment] 2022-06-03 22:40
@cgutman I'm not sure why but 9daf7b5a362f2aff90e61ad16f8390ec637e5f5b breaks on LibreELEC for the Pi4, on Raspbian it works fine. 

moonlight-qt_4.1.0-1_arm64.deb: works
moonlight-qt_4.1.0-2_arm64.deb: segfaults

Kernel used: Linux kodi 5.10.76 #1 SMP Sat Oct 30 00:03:05 CEST 2021 aarch64 GNU/Linux

The patch seems quite trivial, are there any extra libraries needed for software rendering I may need to inject?
See also https://github.com/veldenb/plugin.program.moonlight-qt/issues/20

Log:
```
Platform 'rpi' running 'libreelec' detected...
Loading profile...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 3840,2160...
Using Qt scale factor 1.28...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.
00:00:00 - SDL Info (0): Compiled with SDL 2.23.0
00:00:00 - SDL Info (0): Running with SDL 2.23.0
00:00:00 - Qt Info: Successfully loaded translation for  "nl"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Debug: "No carrier"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 208 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
Segmentation fault
```

ldd dump of libraries loaded:
```
	/usr/lib/libarmmem-v7l.so (0xf7859000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0xf77ee000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0xf7606000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0xf755b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0xf7548000)
	librt.so.1 => /usr/lib/librt.so.1 (0xf7531000)
	libopus.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libopus.so.0 (0xf74d3000)
	libvchiq_arm.so => /usr/lib/libvchiq_arm.so (0xf74bd000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0xf748c000)
	libXv.so.1 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libXv.so.1 (0xf7478000)
	libXext.so.6 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libXext.so.6 (0xf7459000)
	libmmal.so => /usr/lib/libmmal.so (0xf7446000)
	libmmal_core.so => /usr/lib/libmmal_core.so (0xf7428000)
	libmmal_util.so => /usr/lib/libmmal_util.so (0xf7408000)
	libmmal_vc_client.so => /usr/lib/libmmal_vc_client.so (0xf73ed000)
	libbcm_host.so => /usr/lib/libbcm_host.so (0xf73c6000)
	libvcsm.so => /usr/lib/libvcsm.so (0xf73ac000)
	libvcos.so => /usr/lib/libvcos.so (0xf7393000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0xf7385000)
	libwayland-client.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libwayland-client.so.0 (0xf736a000)
	libX11.so.6 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libX11.so.6 (0xf7244000)
	libQt5QuickControls2.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5QuickControls2.so.5 (0xf720c000)
	libQt5Quick.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Quick.so.5 (0xf6d7c000)
	libQt5Svg.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Svg.so.5 (0xf6d20000)
	libQt5Widgets.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Widgets.so.5 (0xf6755000)
	libQt5Gui.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Gui.so.5 (0xf61ac000)
	libQt5Qml.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Qml.so.5 (0xf5dbc000)
	libQt5Network.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Network.so.5 (0xf5c15000)
	libQt5Core.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5Core.so.5 (0xf5732000)
	libGLESv2.so.2 => /usr/lib/libGLESv2.so.2 (0xf5729000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0xf5700000)
	libEGL.so.1 => /usr/lib/libEGL.so.1 (0xf56de000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf5559000)
	libm.so.6 => /usr/lib/libm.so.6 (0xf54f0000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xf54c3000)
	libc.so.6 => /usr/lib/libc.so.6 (0xf5384000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0xf5365000)
	libz.so.1 => /usr/lib/libz.so.1 (0xf5351000)
	/lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0xf7d89000)
	libmmal_components.so => /usr/lib/libmmal_components.so (0xf5336000)
	libcontainers.so => /usr/lib/libcontainers.so (0xf5315000)
	libffi.so.7 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libffi.so.7 (0xf52fd000)
	libxcb.so.1 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libxcb.so.1 (0xf52cc000)
	libQt5QuickTemplates2.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5QuickTemplates2.so.5 (0xf5183000)
	libQt5QmlModels.so.5 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libQt5QmlModels.so.5 (0xf5100000)
	libatomic.so.1 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libatomic.so.1 (0xf50e7000)
	libpng16.so.16 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libpng16.so.16 (0xf50a8000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0xf4fd9000)
	libmd4c.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libmd4c.so.0 (0xf4fbb000)
	libgssapi_krb5.so.2 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libgssapi_krb5.so.2 (0xf4f6b000)
	libdouble-conversion.so.3 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libdouble-conversion.so.3 (0xf4f47000)
	libicui18n.so.67 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libicui18n.so.67 (0xf4ccf000)
	libicuuc.so.67 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libicuuc.so.67 (0xf4b31000)
	libpcre2-16.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libpcre2-16.so.0 (0xf4aa5000)
	libzstd.so.1 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libzstd.so.1 (0xf49d8000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xf488c000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0xf4857000)
	libgbm.so.1 => /usr/lib/libgbm.so.1 (0xf484a000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0xf482e000)
	libXau.so.6 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libXau.so.6 (0xf481b000)
	libXdmcp.so.6 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libXdmcp.so.6 (0xf4804000)
	libkrb5.so.3 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libkrb5.so.3 (0xf4749000)
	libk5crypto.so.3 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libk5crypto.so.3 (0xf470d000)
	libcom_err.so.2 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libcom_err.so.2 (0xf46fa000)
	libkrb5support.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libkrb5support.so.0 (0xf46df000)
	libicudata.so.67 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libicudata.so.67 (0xf2bb9000)
	libbsd.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libbsd.so.0 (0xf2b97000)
	libkeyutils.so.1 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libkeyutils.so.1 (0xf2b83000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0xf2b5d000)
	libmd.so.0 => /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/libmd.so.0 (0xf2b42000)
```

**Comment by cgutman** [comment] 2022-06-04 02:22
Can you run it under gdb and get a backtrace? What version of SDL are you building with?

**Comment by veldenb** [comment] 2022-06-04 14:54
@cgutman  I do not compile it myself, I use the pre-build (manually extracted) binary from: https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/raspbian buster/main armhf moonlight-qt armhf 4.1.0-2 [2284 kB]. The extra libraries needed are extracted from Debian Buster. Details can be found here: https://github.com/veldenb/plugin.program.moonlight-qt/tree/main/resources/build/rpi
(offtopic, an AppImage version for the Pi would be easier to work with on LibreELEC)

A backtrace using gdb:
```
Platform 'rpi' running 'libreelec' detected...
Loading profile...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 3840,2160...
Using Qt scale factor 1.28...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "armv8a-libreelec-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./moonlight-qt...
(No debugging symbols found in ./moonlight-qt)
(gdb) run
Starting program: /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/bin/moonlight-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.
00:00:00 - SDL Info (0): Compiled with SDL 2.23.0
00:00:00 - SDL Info (0): Running with SDL 2.23.0
[New Thread 0xf3a8c380 (LWP 8545)]
00:00:00 - Qt Info: Successfully loaded translation for  "nl"
[New Thread 0xf25e9380 (LWP 8548)]
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
[New Thread 0xf0fff380 (LWP 8549)]
[New Thread 0xf05ff380 (LWP 8550)]
00:00:00 - Qt Debug: "No carrier"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 208 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Sharing DRM FD with SDL

Thread 1 "moonlight-qt" received signal SIGSEGV, Segmentation fault.
__GI_strcmp (p1=<optimized out>, p2=<optimized out>) at strcmp.c:43
43	strcmp.c: No such file or directory.
(gdb) bt
#0  __GI_strcmp (p1=<optimized out>, p2=<optimized out>) at strcmp.c:43
#1  0x0090b9c6 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by veldenb** [comment] 2022-06-05 12:55
Maybe the patch is incompatible with HDR in some situations. Normally the next log line would be 
```SDL Info (0): Using direct rendering for HDR support```

Log version 4.1.0-1
```
Platform 'rpi' running 'libreelec' detected...
Loading profile...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 3840,2160...
Using Qt scale factor 1.28...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.
00:00:00 - SDL Info (0): Compiled with SDL 2.23.0
00:00:00 - SDL Info (0): Running with SDL 2.23.0
00:00:00 - Qt Info: Successfully loaded translation for  "nl"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Debug: "No carrier"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 208 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
00:00:00 - SDL Info (0): Using direct rendering for HDR support
00:00:00 - SDL Error (0): drmModeObjectSetProperty(HDR_OUTPUT_METADATA) failed: 13
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
00:00:00 - SDL Info (0): Using DRM renderer
00:00:00 - FFmpeg: [hevc @ 0x25d2f60] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
```

**Comment by veldenb** [comment] 2022-06-06 00:30
@cgutman I think I found the culprit, it might be a bug in SDL. Following the stack trace back to SDL it's looks like SDL 2.0.22 introduced some new code: https://github.com/libsdl-org/SDL/pull/5296/commits/e02b454e7b6a18a0993a997ba19f1b83ee8cc2f6 to check for accelerated OpenGL.

If I rebuild the rpi version of moonlight-qt using SDL 2.0.20 moonlight-qt works as expected. On SDL  2.0.22 and 2.0.23 it segfaults.

Maybe you can work around it somehow?


Log moonlight-qt master branch SDL 2.0.20:
```
Platform 'rpi' running 'libreelec' detected...
Loading profile...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 3840,2160...
Using Qt scale factor 1.28...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - Qt Info: Unable to detect Wayland or X11, so EGLFS will be used by default. Set QT_QPA_PLATFORM to override this.
00:00:00 - Qt Info: Setting display mode by default. Set QT_QPA_EGLFS_ALWAYS_SET_MODE=0 to override this.
00:00:00 - SDL Info (0): Compiled with SDL 2.0.20
00:00:00 - SDL Info (0): Running with SDL 2.0.20
00:00:00 - Qt Info: Successfully loaded translation for  "nl"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Debug: "No carrier"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 213 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
00:00:00 - SDL Info (0): Using direct rendering for HDR support
00:00:00 - SDL Error (0): drmModeObjectSetProperty(HDR_OUTPUT_METADATA) failed: 13
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
00:00:00 - SDL Info (0): Using DRM renderer
00:00:00 - FFmpeg: [hevc @ 0x17b3e60] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
```
