### ISSUE TITLE
Moonlight always streams in H.264 with RTX 3080 host GPU moonlight-stream/

### ISSUE THREAD

**Issue by lanehartlee** [moonlight-stream/moonlight-qt#471] opened 2020-11-11 02:07 UTC
Moonlight always streams in H.264 with RTX 3080 host GPU moonlight-stream，There is no problem using 980ti, h265 can be used

**Comment by cgutman** [comment] 2020-11-11 02:08
Duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/447

**Closed by cgutman** 2020-11-11 02:08 UTC
