### ISSUE TITLE
Image freezing after some time playing on macOS

### ISSUE THREAD

**Issue by Bisewski** [moonlight-stream/moonlight-qt#801] opened 2022-06-01 18:31 UTC
Image freezing after some time playing on macOS. Sound and controls keep working. Disconnect and reconnect solves the issue temporarily.

**Moonlight settings**

Resolution: 4K 60 FPS
Bitrate: 150 Mbps
Window mode: Window
V-sync: On
Framerate: On

**Client PC details**
 - OS: macOS 12.4
 - Moonlight Version: 4.1.0
 - GPU: Radeon Pro 570X

**Server PC details**
 - OS: Windows 11 Pro 212H
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 512.95
 - GPU: GeForce GTX 1080 Ti
 - Antivirus and firewall software: Windows Defender

**Moonlight Logs**
[Moonlight-1654094858.log](https://github.com/moonlight-stream/moonlight-qt/files/8817960/Moonlight-1654094858.log)

**Comment by cgutman** [comment] 2022-06-02 00:02
Probably a duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

Let me know if turning off hardware-accelerated GPU scheduling on the host doesn't fix it.

**Closed by cgutman** 2022-06-02 00:02 UTC
