### ISSUE TITLE
Mac os version work with micro lags, very bad!

### ISSUE THREAD

**Issue by GreypaX** [moonlight-stream/moonlight-qt#420] opened 2020-07-05 22:00 UTC
i have iMac 2019 and CPU core i9 9900k, 32 gb DDR memory, video: Radeon Pro 580X 8gb., Ethernet 1000 mbps.

in bootcamp (windows 10) Moonlight works very good 4K and 60 FPS! in the Mac OS very bad, i have micro lags, not stable FPS! why? Also i tested moonlight in iOS and there all good, stable 60 fps with 1920p.

**Comment by cgutman** [comment] 2020-07-06 06:01
Duplicate of #414

**Closed by cgutman** 2020-07-06 06:01 UTC
