### ISSUE TITLE
How to add pair/unpair/list actions for windows command line ？

### ISSUE THREAD

**Issue by liypgithub** [moonlight-stream/moonlight-qt#270] opened 2019-09-14 08:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cgutman** [comment] 2019-09-15 01:49
Duplicate of #209

**Closed by cgutman** 2019-09-15 01:49 UTC
