### ISSUE TITLE
Black bars around image, even with matching resolutions

### ISSUE THREAD

**Issue by DoctorWhoof** [moonlight-stream/moonlight-qt#614] opened 2021-06-19 16:54 UTC
**Describe the bug**
My remote PC is connected to a 4K TV. However, even if the TV is off and I change the resolution to what I need (my laptop's, which is 2880x1800) on both the remote Windows and Moonlight's streaming settings, I get an image that does not fill the entire laptop's monitor and has black bars around it (see screenshot below). No settings can be changed in Moonlight that fix the issue, it can only be fixed by changing the remote machine's resolution, which needs to be always at 4K (3840x2160), which is clearly less than ideal.

**Steps to reproduce**
- Plug remote machine to a 4K display. Keep display off (if completely unplugged I get a black screen, which seems related to a separate problem)
- Set remote machine's resolution to something below 4K, like 2880x1800
- Set Moonlight resolution to match (although in reality it won't matter, it's just what I would do to not waste bandwidth).
- You'll see the remote machine's screen at the top left corner, but it won't fill up the entire available screen resolution.

**Screenshots**
Remote machine as viewed on Moonlight:
![Screen Shot 2021-06-19 at 9 25 37 AM](https://user-images.githubusercontent.com/6250116/122649285-ff0a0d80-d0e1-11eb-940e-5c5aaa805e42.png)
Moonlight settings:
<img width="414" alt="Screen Shot 2021-06-19 at 9 26 18 AM" src="https://user-images.githubusercontent.com/6250116/122649298-11844700-d0e2-11eb-92b5-23e50799d1e4.png">

**Affected games**
Issue affects anything, including viewing the Windows desktop which is my primary use (running non game applications).

**Other Moonlight clients**
- Yes, same issue happens when viewing from the iOS app.

**Moonlight settings (please complete the following information)**
- Resolution (2880x1800) matches both laptop and the remote machine.
- Setting the resolution to 4K on remote machine fixes the issue.
- Setting the resolution on Moonlight doesn't seem to affect the issue. It's the remote machine's resolution that causes the problem.

**Client PC details (please complete the following information)**
 - OS: macOS Big Sur 11.3
 - Moonlight Version: 3.1.3
 - GPU: Intel Iris Pro

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro version 2004
 - GeForce Experience version: 3.22.0.32
 - Nvidia GPU driver: 466.77
 - Antivirus and firewall software: Windows Defender and Windows Firewall only.

**Moonlight Logs (please attach)**
[Moonlight-1624119506.log](https://github.com/moonlight-stream/moonlight-qt/files/6681038/Moonlight-1624119506.log)

**Comment by cgutman** [comment] 2021-06-20 15:40
The problem is that you're changing resolutions in the Windows Display options. Setting the resolution using the NVIDIA Control Panel correctly scales the output. You may need to toggle it back to non-native and then native again with NVIDIA Control Panel for the change to take.

Duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/485

**Closed by cgutman** 2021-06-20 15:40 UTC

**Comment by DoctorWhoof** [comment] 2021-06-21 03:11
Yes, that worked.
Weird that changing what should be the same setting in two places gives two different results, but hey, it's Windows after all.

Thanks!
