### ISSUE TITLE
Does it support vibration?

### ISSUE THREAD

**Issue by ZerOri** [moonlight-stream/moonlight-qt#287] opened 2019-11-09 05:10 UTC
**Is your feature request related to a problem? Please describe.**
Can it support vibration of Xbox wireless controler?

**Describe the solution you'd like**
When I use Xbox wireless controler, I find that it can't support vibration.

**Comment by cgutman** [comment] 2019-11-09 23:13
Vibration is supported, however I find that sometimes it stops working and you need to reboot the host PC to fix it.

This issue may also be a duplicate of #279 if you're on macOS.

You can get more help on our [Discord server](https://discord.gg/MySTSdq)

**Closed by cgutman** 2019-11-09 23:13 UTC
