### ISSUE TITLE
Moonlight unable to open display

### ISSUE THREAD

**Issue by RetroChemo** [moonlight-stream/moonlight-qt#208] opened 2019-04-08 06:25 UTC
**Describe the bug**
It simply won't start. Gives error in terminal.

**Steps to reproduce**
All I did was install the snap with "sudo snap install moonlight" and then after that, run it.

**Client PC details**
 - OS: [Solus 4 (Linux)]
 - Moonlight Version: [v0.10.0]

**Moonlight Logs**

+ case "$SNAP_ARCH" in
+ ARCH=x86_64-linux-gnu
++ grep 'OpenGL vendor'
++ glxinfo
No protocol specified
Error: unable to open display :0
+ VENDOR=
+ export VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ VDPAU_DRIVER_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/vdpau
+ export LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ LIBVA_DRIVERS_PATH=/snap/moonlight/96/usr/lib/x86_64-linux-gnu/dri
+ [[ '' == *\N\V\I\D\I\A* ]]
+ [[ '' == *\X\.\O\r\g* ]]
+ exec /snap/moonlight/96/usr/bin/moonlight
No protocol specified
00:00:00 - Qt Warning: QXcbConnection: Could not connect to display :0
00:00:00 - Qt Critical: Could not connect to any X display.

**Comment by cgutman** [comment] 2019-04-08 08:21
I think this is a duplicate of https://github.com/maxiberta/moonlight-snap/issues/3 (which itself duplicates https://bugs.launchpad.net/snapd/+bug/1819318)

There is a workaround there (install the `core` snap). It's slated to be fixed in snapd 2.39.

**Closed by cgutman** 2019-04-08 08:21 UTC
