### ISSUE TITLE
Gamestream is loading rtx3070 about 90-98% while streaming desktop with any drivers newer than 457.51

### ISSUE THREAD

**Issue by Stalkeork** [moonlight-stream/moonlight-qt#517] opened 2021-02-10 03:05 UTC
NVIDIA Server Streaming Component is loading rtx3070 about 90-98% using moonlight client while streaming desktop/games/progs with any drivers newer than 457.51, uses 3d acceleration (why) to encode video (watch screenshots), while 457.51 and older drivers correctly uses VIdeo Encode. Done all nvidia support says like ddu'ed drivers, trying to launch under new pc user, installed (old) driver patches, then they asked what client do i use for gamestream, and than thay made "nonono, nothing we can do with moonlight" (im thinking - its serverside drivers problems) . 

aorus elite b550m 
ryzen 3600x
palit gamingpro 3070
32gb ram hyperx
win 10 pro
![571.51 and older drivers behavior](https://user-images.githubusercontent.com/46562145/107458669-97f1b080-6b65-11eb-9dd6-fad62eea72d8.png)
![any latest drivers newer than 571.51](https://user-images.githubusercontent.com/46562145/107458674-9b853780-6b65-11eb-9b4f-c45ae983388c.png)

**Comment by Stalkeork** [comment] 2021-02-11 02:35
fixed it by disabling Hardware accelerated GPU scheduling in windows. Updated ticket to nvidia, hope they'll fix that issue

**Comment by cgutman** [comment] 2021-02-27 04:11
Okay, since this looks like an Nvidia bug (not Moonlight), I'll close it.

Thanks documenting the workaround for others to find later!

**Closed by cgutman** 2021-02-27 04:11 UTC

**Comment by skarekrow** [comment] 2022-08-25 20:21
Still seeing this with current drivers (HAGS disabled) on 516.94. I believe it's the root cause behind #853 as I can see with Parsec it's hovering ~27% and it's stable, but Moonlight spikes to 100% and crashes very shortly thereafter.

**Comment by skarekrow** [comment] 2022-08-25 22:02
Using Sunshine this issue disappears, but different ones take their place 😂 so atleast this doesn't seem to be related to nvenv but instead GFE and something it's doing I suppose. Not sure how to solve that besides rolling all the way back to much older drivers.

**Comment by comienzo2093** [comment] 2023-01-29 06:29
same issue here
