### ISSUE TITLE
Video artifacts, audio glitch

### ISSUE THREAD

**Issue by EnergiaBuran** [moonlight-stream/moonlight-qt#172] opened 2019-02-03 23:40 UTC
**Describe the bug**
Frequent video artifacts when playing Hearthstone (and probably other games) and occasional audio stutter that also causes video lag for few seconds. It's basically unplayable.

**Steps to reproduce**

**Screenshots**

**Affected games**
Hearthstone and I remember Nier Automata some months back, so probably all games.

**Moonlight settings (please complete the following information)**
- If so, which settings have been changed?
tried native 1440x900 res and 1080p, 60 fps, 20 mbps
- Does the problem still occur after reverting settings back to default?
yes

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803]
macOS 10.14.2
macbook pro 13 2017 touch bar
 - Moonlight Version: [e.g. v0.2.0]
0.8.1

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1803]
Win 10 1709
 - GeForce Experience version: [e.g. 3.16.0.140]
3.16.0.140
 - Nvidia GPU driver: [e.g. 417.35]
417.71
[Moonlight-1549234231.log](https://github.com/moonlight-stream/moonlight-qt/files/2826128/Moonlight-1549234231.log)

**Moonlight Logs (please attach)**
attached

Other:
5ghz router in the same room as the laptop. Server is connected to the router via cable.
Since I don't remember Moonlight not having video artifacts when I tested it, I wonder if it is normal to have them? Or do others have almost flawless quality, sort of like watching Twitch?

**Comment by cgutman** [comment] 2019-02-06 03:49
This might be a duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/159

Please try disabling macOS Location Services as mentioned here: https://github.com/moonlight-stream/moonlight-qt/issues/159#issuecomment-452675992

**Comment by EnergiaBuran** [comment] 2019-02-11 03:16
No audio and video glitches after disabling Location Services (also updated to 10.14.3, but don't think it matters) from a few hours of playing HS. Amazing. Going to test some more with another game.

Maybe the program should have a warning or the website have a FAQ with this fix (if there isn't one). Either way, thanks.

**Comment by cgutman** [comment] 2019-02-13 03:32
Added it to the troubleshooting section on the wiki and the release notes of Moonlight.

**Closed by cgutman** 2019-02-13 03:32 UTC
