### ISSUE TITLE
Moonlight crashed after about 10mins with Connection Terminated, repeatedly.

### ISSUE THREAD

**Issue by SimonPhilpott** [moonlight-stream/moonlight-qt#746] opened 2022-03-06 18:41 UTC
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
After around 10 mins The connection is terminated with a "Connection Terminated" error message. I am able to re-establigh the streaming connection but the same error happens again after around 10mins.

**Steps to reproduce**
No special steps, this happens for all games

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
Elden Ring, No Mans Sky, Warhammer 3 Total War, State of Decay 2.

**Other Moonlight clients**
I don't have those installed

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? YES
- If so, which settings have been changed? HEVC H.265 encoding
- Does the problem still occur after reverting settings back to default? Yes

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Windows 11 21H2
 - Moonlight Version: [e.g. v0.9.0] 3.2.0
 - GPU: [e.g. Intel HD Graphics 520] Intel Iris Plus

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Windows 11 21H2
 - GeForce Experience version: [e.g. 3.16.0.140] 3.25.0.84
 - Nvidia GPU driver: [e.g. 417.35] 511.79
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall] Windows Defender / Windows Firewall

**Moonlight Logs (please attach)**
[Moonlight-1646587483.log](https://github.com/moonlight-stream/moonlight-qt/files/8193272/Moonlight-1646587483.log)

**Additional context**
Anything else you think may be relevant to the issue

**Comment by cgutman** [comment] 2022-03-06 19:40
This might be the GPU driver bug introduced in the R495 series. Try disabling hardware-accelerated GPU scheduling on your host PC and see if the issue goes away.

**Comment by SimonPhilpott** [comment] 2022-03-12 20:36
Ah no, already off. 

I've tried downgrading my driver's to 472.12 and that hasn't worked either. That's supposed the be a rock solid driver release. I wonder if it's Geforce experience? I can't get that to stick downgraded it updates itself and I can't even block that with firewall settings.

**Comment by SimonPhilpott** [comment] 2022-03-13 09:38
[Moonlight-1647117608.log](https://github.com/moonlight-stream/moonlight-qt/files/8239265/Moonlight-1647117608.log)
Termination reason, 0x8003001c. No idea what this means, however there are a lot of dropped an unrecoverable and audio frames. I have a wired link to my router for the client and host tested at 90Mbps, I have Moonlight set to 50Mbps. 1080p, 60fps.

"00:14:07 - SDL Info (0): Server notified termination reason: 0x8003001c
00:14:07 - SDL Error (0): Connection terminated: -2147287012
00:14:07 - SDL Info (0): Quit event received
00:14:07 - SDL Info (0): Failed to send ENet control packet
00:14:07 - SDL Info (0): Loss Stats: Transaction failed: 10035
00:14:07 - SDL Info (0): Global video stats"

**Comment by SimonPhilpott** [comment] 2022-03-13 21:48
Okay so. I think I've fixed this, to help others. 

I followed this guide, https://www.reddit.com/r/cloudygamer/comments/tcr4e4/how_to_perfectly_optimize_your_moonlight_setup/

It must have been either an adapter being put to sleep to save power or Windows defender being aggressive.

**Comment by d3smo** [comment] 2022-03-16 10:34
I've the same issue since two weeks playing God of War on my Nvidia Shield pro 2001 (4K Max settings), streaming from my desktop PC (W11, AMD 3900X, RTX 3080) on 1GB Lan  connexion. What settings from the Reddit topic you've use to solve your problem, the guy who wrote the topic setup a lot of stuff are their all needed, or is it a specific setting that solve the issue ?

**Comment by SimonPhilpott** [comment] 2022-03-16 11:37
The two main thing I did was disable the energy saving features on my host
and client LAN adapters and turn off defender on both too.

I'll reintroduce defender on both and see if the issue comes back.

**Comment by d3smo** [comment] 2022-03-27 11:48
Finally i found a solution to my issue by just turning off  "Hardware GPU Scheduling" on my computer, this issue is reported here https://www.reddit.com/r/ShieldAndroidTV/comments/r9vauz/moonlight_image_rarely_freezes_but_game_is_still/

**Comment by cgutman** [comment] 2022-05-07 19:41
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

**Closed by cgutman** 2022-05-07 19:41 UTC

**Comment by minksW** [comment] 2023-08-16 20:03
help
