### ISSUE TITLE
"nprotect game guard" blocks keyboard and mouse when enabled

### ISSUE THREAD

**Issue by phoenix91love** [moonlight-stream/moonlight-qt#1031] opened 2023-07-04 02:35 UTC
Connect moonlight to sunshine, when "nprotect game guard" is run by another software, can't move mouse and use keyboard.
But moonlight connect to geforce running normal. 
I have use moonlight and sunshine latest version (moonlight 4.3.1, sunshine 2.0)

**Comment by cgutman** [comment] 2023-07-21 02:41
Duplicate of https://github.com/LizardByte/Sunshine/issues/1416

**Closed by cgutman** 2023-07-21 02:41 UTC
