### ISSUE TITLE
  HUAWEI TV unable to connect not available   ，HarmonyOS1.0.1.32,Can install , cannot connect 

### ISSUE THREAD

**Issue by wtugug** [moonlight-stream/moonlight-qt#439] opened 2020-09-10 10:14 UTC
HUAWEI TV unable to connect not available   ，HarmonyOS1.0.1.32,Can install , cannot connect

**Comment by cgutman** [comment] 2020-09-11 17:22
Please do not file multiple issues for the same problem.

This is a duplicate of https://github.com/moonlight-stream/moonlight-android/issues/877

**Closed by cgutman** 2020-09-11 17:22 UTC
