### ISSUE TITLE
NEED Limit to which displayer while streaming through Touchscreen Mode 

### ISSUE THREAD

**Issue by none-id** [moonlight-stream/moonlight-qt#518] opened 2021-02-11 05:27 UTC
This maybe a bug, because the streaming is only on one displayer, but when turn on touchscreen mode, the whole controling area is all the two displayer, here is an example pic of this bugs. 
![image](https://user-images.githubusercontent.com/45704666/107604965-b098be00-6c6c-11eb-9241-3f6df8452d62.png)
So, it need to add a limit area to using the Touchscreen Mode flunetly.

**Comment by cgutman** [comment] 2021-02-27 04:09
Yeah, if I'm understanding correctly you're referring to the broken behavior of absolute mouse input when the host PC has multiple displays. So this bug is a duplicate of https://github.com/moonlight-stream/moonlight-common-c/issues/49

Moonlight sends the coordinates correctly, but GeForce Experience is translating them incorrectly (scaling them to the entire desktop workspace instead of just the monitor being streamed). Unfortunately this is Nvidia's bug, so we cannot fix it ourselves. A client-side workaround is also not possible because we lack the information about the monitor layout required to doing the fixups on our end.

**Closed by cgutman** 2021-02-27 04:09 UTC

**Comment by none-id** [comment] 2021-02-28 08:36
yea, thanks for reply.
