### ISSUE TITLE
Running on Raspberry PI

### ISSUE THREAD

**Issue by Prendaloth** [moonlight-stream/moonlight-qt#160] opened 2019-01-09 21:39 UTC
Is there any way to make moonlight Qt run on raspberry PI ?

**Comment by cgutman** [comment] 2019-01-11 04:13
You can install the Flatpak on ARM, but you won't have hardware accelerated video AFAIK because the Pi only supports OpenMAX video acceleration, not VAAPI or VDPAU which this client supports. I don't think there's any support in Flatpak for OpenMAX decoding.

Additionally, you would likely need X running to display the client on screen, which you may not have if you're launching Moonlight straight from the terminal console.

**Comment by Prendaloth** [comment] 2019-01-15 20:13
I wanted moonlight Qt because it supports 120hz  and 4k. 

Can moonlight Qt run on ARM ?  If yes, is there any ARM board like raspberry pi capable of decoding 1080p 120hz or 4k@60hz ?

**Comment by cgutman** [comment] 2019-01-18 02:17
Most ARM boards don't use VAAPI or VDPAU standards for decoding. They use OMX or other specially created solutions that Moonlight Qt doesn't support.

I think you can use `-unsupported -fps 120` option though on Moonlight Embedded and it should work as long as the hardware is capable of it.

**Comment by cgutman** [comment] 2019-04-16 08:29
I added support for MMAL hardware accelerated video decoding for the Raspberry Pi https://github.com/moonlight-stream/moonlight-qt/commit/9c76700f747f8c935801f5b8b3e54626eb459c51

It's still not possible to run without X, but I believe I may be able to circumvent that with a special Qt platform option. Still investigating that.

**Comment by Garconepique** [comment] 2019-05-01 15:03
Thanks for all the work cgutman!

I've been trying the latest version (Moonlight PC v0.10.1 via flatpak) on a Raspberry pi 3b+ running Raspbian Stretch (with desktop). Initially it did not seem to start at all, but when I switched over to experimental GL Drivers (Full KMS or Fake KMS) it started.  Obviously it wasn't able to find hardware accelerated decoding so game-play was very choppy and made it unplayable. 

Will MMAL fix this?

**Comment by cgutman** [comment] 2019-05-02 03:43
Yes, MMAL fixes this. It's not ready yet mainly due to packaging headaches since it requires that we custom build FFmpeg and Moonlight against Raspberry Pi libraries that aren't part of any Flatpak runtime.

**Comment by yukatan** [comment] 2019-10-05 21:45
How is the state of this??? Any news about running moonlight-qt over raspberry???

**Comment by discordianfish** [comment] 2019-11-27 14:25
Just tried this and even though I'm using 1.1.1 where 9c76700 should be included, I get 'no hw support' message and everything is very slow and forcing hw fails. Any special config that is needed? Or is this just not there yet?

**Comment by cgutman** [comment] 2019-11-27 14:41
You'll need to link against an FFmpeg build with MMAL enabled to get hardware acceleration and make sure your GPU is allocated at least 128 MB of RAM.

**Comment by discordianfish** [comment] 2019-11-27 21:46
@cgutman Ah thanks for the answer. I assume I need to build that myself, or are there prebuilt packages (e.g flatpak) for this already?

**Comment by discordianfish** [comment] 2019-11-27 22:11
I just realize that this would still only give me h264 stream - like moonlight-embedded does. What I really want is 4k streaming which the rpi4 only supports for h265..

**Comment by cgutman** [comment] 2019-11-28 00:30
I don't think HEVC support is upstreamed yet for the Pi 4. I believe it's supposed to be based on V4L2.

**Comment by discordianfish** [comment] 2019-11-28 10:12
@cgutman Apparently there are patches for ffmpeg to support it and libelec use them to support h265 playback: https://forum.kodi.tv/showthread.php?tid=345112 But I'm confused by all the patches and different forks of ffmpeg and which one actually support h265 in hardware.

**Comment by michellabbe** [comment] 2020-01-25 11:20
I'd be happy with h264 support for a while so I can get rid of moonlight-embedded (it works fine but it's a pain via command line, and I'm sick of building a separate icon for every single game).

Using a RPi4 (256 MB allocated for GPU) with raspbian buster, ffmpeg seems to support h264_mmal by default now.  However, Moonlight-QT 1.2.0 (Flatpak) still doesn't detect any hardware accelerated H.264 video decoder.

[ffmpeg_decoders.txt](https://github.com/moonlight-stream/moonlight-qt/files/4111965/ffmpeg_decoders.txt)
[flatpak_log.txt](https://github.com/moonlight-stream/moonlight-qt/files/4111966/flatpak_log.txt)

Is it just me? or do we still need to recompile some stuff manually to get MMAL support?

This ffmpeg [bug report](https://trac.ffmpeg.org/ticket/8018) mentions an issue with MMAL on RPI4 which is fixed with a firmware upgrade, but I tested mp4 playback with h264_mmal and it seems to work just fine so I believe my firmware is fine.

**Comment by cgutman** [comment] 2020-01-25 17:51
The reason it doesn't work out of the box is that the Flatpak is self-contained by design and doesn't use the libraries on the host (like ffmpeg). The included build of ffmpeg in the latest flatpak packages does not include MMAL.

@michellabbe I have been experimenting with a MMAL-enabled Moonlight Flatpak for the Pi in the Flathub Beta repo. Give it a try and let me know how it works for you.

Install using:
```
flatpak install https://dl.flathub.org/beta-repo/appstream/com.moonlight_stream.Moonlight.flatpakref
```
Run using: `flatpak run --branch=beta com.moonlight_stream.Moonlight`

**Comment by michellabbe** [comment] 2020-01-25 18:50
Thanks!  I wish I asked earlier :)

The fun part is since I installed the beta version,

```
flatpak run com.moonlight_stream.Moonlight
flatpak run --branch=beta com.moonlight_stream.Moonlight
```
now both have MMAL working (so I guess the beta installed on top of non-beta version)

Both version also don't have sound ("Failed to open audio device" when starting stream).

I first thought it was hdmi_drive=2 mssing in /boot/config.txt, but it's already in there, and sound works fine in Steam Link app.

Does audio work on your side?

**Comment by cgutman** [comment] 2020-01-25 19:02
No, I think it's because PulseAudio is not installed on Raspbian by default.

**Comment by michellabbe** [comment] 2020-01-28 03:40
I'm not 100% sure by now, but I think PulseAudio was already installed.

for the records:
`sudo apt-get install pulseaudio` (and reboot)

According to [this article](http://docs.flatpak.org/en/latest/sandbox-permissions.html), applications that are run with Flatpak are sandboxed and, by default, don't have access to host services, including PulseAudio.

There's alot of stuff I don't understand in this article but I think you need to add `--socket=pulseaudio` in the `finish-args` section of the manifest file when building.  Does that make sense?

I also tried:
```
PULSE_SERVER=unix:/tmp/pulse-PKdhtXMmr18n/native
flatpak run --branch=beta com.moonlight_stream.Moonlight
```
(must not `sudo` the flatpak run)

With `PULSE_SERVER` variable set, I don't get the error msg anymore when initiating stream, but the actual audio is terrible:  I need to raise host volume pretty much to max to hear some sound and it looks like a verry very crappy bitrate (sounds like static at first, but if you listen carefully you can recognize expected audio playing).

**Comment by cgutman** [comment] 2020-01-28 03:58
PulseAudio is explicitly allowed by `--socket=pulseaudio` in the Flatpak manifest, otherwise audio wouldn't work at all in the Flatpak.

I suspect PA needs some buffer size tweaks or something to avoid underruns on the Pi. In any case, you'll likely have better luck building Moonlight Qt natively, rather than using the Flatpak. That way it can just use ALSA directly like everything else on Raspbian.

**Comment by cgutman** [comment] 2020-02-06 07:13
I finally got Moonlight packaged for Raspbian with my patched low-latency build of FFmpeg. Please give it a try and tell me what you think.

```
echo "deb https://dl.bintray.com/cgutman/moonlight-raspbian buster main" | sudo tee /etc/apt/sources.list.d/moonlight-raspbian.list 
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
sudo apt update
sudo apt install moonlight
```

Known issues:
- Only works if X is running (for now)
- _You must set your GPU memory to 128 MB or greater in `raspi-config` first_

**Comment by michellabbe** [comment] 2020-02-06 14:03
Awesome news! :)

You should rename the executable (e.g. to **moonlight-qt**) because right now it conflicts with moonlight-embedded:

- Typing `moonlight` in CLI launches moonlight-embedded.
- Default shortcut for Moonlight-QT doesn't open anything (most likely trying to start moonlight-embedded in the background, with no argument)
- `/usr/bin/moonlight` does launch Moonlight-QT
- Shortcut also works after editing with `Exec=/usr/bin/moonlight`

Seems to work pretty much fine so far.  Still no sound though (and only in moonlight-qt).

[moonlight-qt_20200206084200.txt](https://github.com/moonlight-stream/moonlight-qt/files/4165399/moonlight-qt_20200206084200.txt)


Btw, do you happen to know if there's a way to "`Alt`+`Tab`" back to PIXEL (lxde) when in the middle of streaming session (e.g. to adjust volume, check log or whatever)?  The only thing I can do right now is exit streaming (`Ctrl`+`Alt`+`Q`) and then hit the "Play" button to get back to streaming session.

**Comment by michellabbe** [comment] 2020-02-11 05:06
I gave it another try with a fresh reinstall of Raspbian buster (2020-02-05-raspbian-buster.img).

When I start a streaming session, I get no error and I do get sound but it's very crappy (just like what I mentioned before, with the Flatpak version and `PULSE_SERVER` variable set).

Again, sound works fine in Chromium and SteamLink streaming from the same host.

Same behavior on both RPi3 and RPi4.

**Comment by cgutman** [comment] 2020-02-12 06:05
@michellabbe Please test again with the latest package in the repository (1.2.1-2) on the RPi 4.

It will now run with or without X, audio is fixed, and various other bugs are fixed too.

**Comment by michellabbe** [comment] 2020-02-12 13:43
Just did a quick test and I confirm audio works fine now.  Thanks!
I'll use it more in the next days.

Was the default shortcut supposed to update itself to include full path (`Exec=/usr/bin/moonlight`)?

**Comment by michellabbe** [comment] 2020-02-12 22:26
Screen tearing is quite noticeable when scrolling the list of available games (I have about 40 titles on my main host).  Is this normal?  It had caught my attention with the Flatpak version as well.

V-Sync seems to be working properly: I don't see such tearing during game streams.  It looks more like some optimisation issue in the Moonlight UI itself.

Also, in the settings windows, you can click in the middle of nowhere and hold the LMB to scroll the page around (even though there is no scrollbars).  This is most likely not expected :)  Same applies for the list of computers (although this one is scrolling up & down only).

The rest seems to be working pretty well so far on the RPi4.

I guess you already noticed that the RPi3 is struggling with 1.2.1-2,  I'm pretty sure it was running much smoother with the previous build.

**Comment by Ronald-Diemicke** [comment] 2020-02-13 04:35
I just got an error trying this on the command line:
SDL Warn (0): Unable to set audio thread to high priority: setpriority() failed
failed to export dumb buffer: Permission denied
Failed to create scanout resource

any ideas?

**Comment by cgutman** [comment] 2020-02-13 05:07
@michellabbe 

- The UI tearing issue is a problem with the graphics stack of the Pi. Even though EGLFS does support V-sync, it doesn't work on the Pi (even with QT_QPA_EGLFS_FORCEVSYNC=1)
- The ability to drag the window contents around is the default behavior from Qt Quick Controls 2 (Flickable.DragAndOvershootBounds). I guess I could change it to Flickable.OvershootBounds instead.
- The Pi 3 issue is known. I think it might be related to my MMAL buffering change.

@Ronald-Diemicke 

What model of Pi? Is it fully updated? Are you running something else like X or Kodi that already has control of the GPU?

**Comment by michellabbe** [comment] 2020-02-13 13:59
@cgutman 
I just realized the drag window content thing applies to other platforms (Windows) as well.

A couple more things (RPi4):

- `Ctrl`+`Alt`+`Shift`+`S` (Open performance stats overlay) doesn't work

- Moonlight starts struggling at 1080p/60fps when you set bitrate over 55 Mbps.  As you keep raising bitrate, mouse lags more in certain scenes, and even starts skipping frames at some point.  It's also not constant during a stream, and more apparent in more complex scenes (e.g. in ESO character selection screen, the mouse lag and frame skipping varies between character scenes).  top shows CPU load is around 30% during the worst parts.

- With resolution set at 1080p, when starting a 720p stream, under X the stream starts windowed instead of fullscreen and we get 2 mouse pointers (not at the same speed) which isn't great.  Doing the same test without X (reboot to console, no X or Kodi running) Moonlight segfaults.  This seems to be the issue **Ronald-Diemicke** is having.

@Ronald-Diemicke: 
Try to launch stream in same resolution you're currently using. I guess Moonlight is unable to switch to a different resolution properly at the moment.

**Comment by Ronald-Diemicke** [comment] 2020-02-16 15:57
@cgutman - so It's a Pi 4 with 4gb of ram. This was straight from the command line - so I don't think anything else was holding the GPU...

@michellabbe - I'll try and give that a shot.

**Comment by cgutman** [comment] 2020-03-13 06:24
I've published a `moonlight-qt` package to replace `moonlight` which can coexist with `moonlight-embedded`. You should all remove `moonlight` and install `moonlight-qt` to continue to get updates.

**Comment by go626201** [comment] 2020-03-13 09:32
@cgutman i just use my raspberry pi 4b with your moonlight-qt.
And i found out that using native resolution(as my monitor is widescreen-2560x1080) will leave the raspbian menubar remained showing. But using the normal 1080p will get fullscreen without left right blackscreen ,but the screen will get abit not clear as the monitor not using the full resolution to show.
![IMG_20200313_172054](https://user-images.githubusercontent.com/9418861/76607870-a8616b80-654f-11ea-9698-2af87f9a95de.jpg)
![IMG_20200313_173019](https://user-images.githubusercontent.com/9418861/76608360-71d82080-6550-11ea-91b9-3f9f065dc860.jpg)

**Comment by michellabbe** [comment] 2020-03-19 02:31
@cgutman current version of Moonlight-QT is running nicely so far, but it's definitely not as smooth as Moonlight-Embedded using the same resolution/fps/bitrate on the same device (RPi4).  I don't know if some more fine-tuning can be done or if it's mostly due to something like Qt that adds an extra layer and it's expected to run a bit slower.

I'm `Ctrl`+`Alt`+`Shift`+`Q` ing and alternating between both without quitting the game and the difference is easy to see at high bitrate (e.g. 1080p, 60fps, vsync on, bitrate = 55000-90000).

Both seem to be skipping frame "due to network" at these bitrates though so it might be the highest the RPi4 can achieve.  Steam Link network test also stops at 90 Mb/s, even though iperf3 shows the device does full gigabit speed (~940 Mbit/sec) without issues.

Btw, does it create a logfile somewhere if you launch it from menu icon?  I couldn't find any.

**Comment by cgutman** [comment] 2020-04-28 03:29
Released in v2.0.0

**Closed by cgutman** 2020-04-28 03:29 UTC
Labels: enhancement

**Comment by cgutman** [comment] 2020-04-29 03:59
I forgot to mention that the package repo has changed to be under the moonlight-stream organization. You can get the updated repo URL from https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Comment by zaptrem** [comment] 2020-06-10 08:32
Now that the SteamLink app has added support for HEVC 4k 60fps on RPI4 is there any chance the same could be enabled here?

**Comment by michellabbe** [comment] 2020-06-10 11:44
> Now that the SteamLink app has added support for HEVC 4k 60fps on RPI4

Huh? What? When? Where?

I've been googling for a dozen mins and still can't find any source of this.

**Comment by michellabbe** [comment] 2020-06-11 02:36
@zaptrem Thanks.

I don't think it makes much sense to keep updating this closed thread so I've created a new request specifically for HEVC support on RPi4.  See https://github.com/moonlight-stream/moonlight-qt/issues/409
