### ISSUE TITLE
Auto-scan games removed

### ISSUE THREAD

**Issue by nk33** [moonlight-stream/moonlight-qt#139] opened 2018-11-26 16:47 UTC
My request is can you please add a feature to NOT include the games in the moonlight list that GFE finds automatically. i have removed all the scan locations from GFE yet it still shows like 60 games i have to sift through.

I just want moonlight to show the games i addmanually through the "add-game" feature in there.

**Comment by Jorys-Paulin** [comment] 2018-11-26 16:52
@nk33 Moonlight only gets the list of game GFE gives it, so it's a GFE bug. Maybe try to remove the games, scan again so it doesn't find anything and so Moonlight doesn't show anything apart from your manually-added games.

**Comment by nk33** [comment] 2018-11-26 16:57
Not really a bug - its just scanning all my games - not going to uninstall 60 games then reinstall them  - cant believe you sggusted this LOL

 is there anyway i can delete the database file? even if i do so will it not just get these games from my steam database? does it look in the steam database?

**Comment by Jorys-Paulin** [comment] 2018-11-26 17:00
@nk33 No no no, just delete the scan locations (which you already did) and hit the scan button. Maybe it'll clear the game list

**Comment by nk33** [comment] 2018-11-26 17:01
apologies - i thought it was obvious i had already tried this lol - sorry

**Comment by nk33** [comment] 2018-11-26 17:12
ok - so i deleted all the locations, force closed GFE, then went back in - the list said 0 - but this was false as all the artwaork was still appearing on the home page of GFE - i acessedwith moonlight and all the games were there too. really frustrating

**Comment by nk33** [comment] 2018-11-26 17:12
the figure then changed to 80 again shortly after

**Comment by decknine** [comment] 2018-11-28 03:17
If you want to remove games from appearing in GFE and also moonlight.

1. Uninstall GFE

2. Navigate to "C:\Users\#USERNAME#\AppData\Local\NVIDIA\NvBackend" and open the config.xml file. From there change the below three settings from "1" to "0" 

  <Setting name='EnableUpdateTypeOPS' value='0' />
  <Setting name='EnableUpdateTypeSOPS' value='0' />
  <Setting name='EnableAutomaticApplicationScan' value='0' />


Next add this line after "ApplicationScanPaths"

<Setting name='ApplicationScanPaths'>
<String>C:\Boot</String>


When finished the config.xml file should look similar to this:
<BackendConfiguration version='1.0'>
  <Setting name='EnableUpdateTypeOPS' value='0' />
  <Setting name='EnableUpdateTypeSOPS' value='0' />
  <Setting name='EnableAutomaticApplicationScan' value='0' />
  <Setting name='OOTBStatus' value='2' />
  <Setting name='AoCrashCount' value='0' />
  <Setting name='CurrentVersion' value='34.0.0.0' />
  <Setting name='CurrentGFEVersion' value='3.16.0.122' />
  <Setting name='CurrentAoVersion' value='39.2.4.0' />
  <Setting name='ApplicationScanPaths'>
<String>C:\Boot</String>
</Setting>
</BackendConfiguration>


When finished, save the document and in the properties set the file to "read only" and apply.

3. Reinstall GFE

Done.

**Comment by cgutman** [comment] 2019-12-23 15:30
Duplicate of #255

**Closed by cgutman** 2019-12-23 15:30 UTC
Labels: enhancement

**Comment by DocMAX** [comment] 2020-10-18 17:00
The issue is, that with this solution the list on moonlight stays emtpy.
