### ISSUE TITLE
mouse not working anymore after updating to moonlight 4.1.0

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#796] opened 2022-05-25 09:16 UTC
Since I updated to moonlight 4.1.0 the mouse doesnt work anymore if you use Moonlight in combination with Lossless Scaling in window mode and legacy capture mode (Lossless Scaling option).

It worked fine with moonlight < 4.1.0, so there mist be some change made in 4.1.0 which breaks this.

What was changed in 4.1.0 for mouse logic? Any way to give option to disable that?

**Comment by cgutman** [comment] 2022-05-25 12:52
> Lossless Scaling in window mode and legacy capture mode (Lossless Scaling option).

Where are you seeing these option names? There are no such “lossless scaling” or “legacy capture mode” options in Moonlight settings. Are you talking about a third party program?

**Comment by makedir** [comment] 2022-05-25 12:57
I said those are specific modes in that specific program. There was something changed it seems in moonlight 4.1.0 which broke compatibility with that program with those parameters. So what was changed? It was just working yesterday still with moonlight < 4.1.0 and now it is not anymore.

**Comment by makedir** [comment] 2022-05-25 13:12
I will revert back to 4.0.9 and see if that fixes it again. Where can I find a download link for 4.0.9? Or was 4.0.0 the one before 4.1.0?

**Comment by makedir** [comment] 2022-05-25 13:19
Yepp. fixed in 4.0.0. just removed 4.1.0 and it works again with 4.0.0

**Comment by makedir** [comment] 2022-05-25 13:48
Nope doesnt do anything, updated to 4.1.0 again, copied SDL2.dll and SDL2_ttf.dll from 4.0.0 into folder started 4.1.0, broken again.

**Comment by makedir** [comment] 2022-05-25 14:18
The problem doesnt seem to be mouse related, actually for whatever reason, the entire video capture is broken in that mode with 4.1.0 and it shows for whatever reason an old video frame, not even sure how that is possible, when you scale.

**Comment by cgutman** [comment] 2022-05-25 14:35
OK, I was able to make some progress. I reproduced the issue locally using your steps (thanks!). The video renderer is unable to be successfully captured using the GDI-based legacy capture API.

I was able to bisect the issue to fd563726f02427621dce3ca44ede689c2942890d. I believe the change from using `D3DSWAPEFFECT_DISCARD` mode to `D3DSWAPEFFECT_FLIPEX` when V-sync is off caused the change in behavior. It appears the GDI-based capture method that is used when "Legacy Capture API" is enabled is incompatible with [modern flip-model swapchains](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/for-best-performance--use-dxgi-flip-model). This is the case for both the DXVA2 renderer using DirectX 9 and the D3D11VA renderer using DirectX 11 (used when streaming with HDR enabled).

Based on that, I could determine that the only reason that "Legacy Capture API" ever worked for you at all is because you were always running with V-sync off. It has never worked with V-sync enabled, since Moonlight has always used FlipEx swap effect for that case. If you go back to 4.0.0 and enable V-sync, you will see that the video freezes just the same way.

I think Moonlight's behavior here is correct, and the issue is that the "Legacy Capture API" is incompatible with Moonlight's video renderer. It only worked for you before by sheer luck, since every other windowed mode used flip swapchains already except that V-sync off case.

I recommend not using the "Legacy Capture API". If you disable Legacy Capture API, the capture works properly for all known cases where it was broken before:
- V-sync off in v4.1.0
- V-sync on in all versions
- HDR mode in v4.0.0 and v4.1.0

**Comment by makedir** [comment] 2022-05-25 14:39
What swapchains? Does Moonlight now uses swapchains for decoding? Because if so, you should make an option to disable those. Intel drivers have a bug which are unstable with using decode swapchains:

https://bugs.chromium.org/p/chromium/issues/detail?id=1107403

Swap chain decode is disabled because of this bug actually in Chrome with certain Intel GPUs.

Please implement an option to revert back the code so it stays compatible. GDI capture mode is faster and uses less CPU usage. It also gives other advantages like proper mouse cursor scaling.

**Comment by cgutman** [comment] 2022-05-25 15:17
> What swapchains?

Swapchains are used by all Direct3D and Vulkan applications. That is how buffers are presented on screen.

https://docs.microsoft.com/en-us/windows/win32/direct3d9/what-is-a-swap-chain-

> Does Moonlight now uses swapchains for decoding? Because if so, you should make an option to disable those. Intel drivers have a bug which are unstable with using decode swapchains:

Moonlight does not use decode swapchains. "Decode swapchains" are not the same thing as "swapchains".

> Please implement an option to revert back the code so it stays compatible. GDI capture (legacy) mode is faster and uses less CPU usage. It also gives other advantages like proper mouse cursor scaling.

I do not plan to introduce an option to use the old swap effect. The old behavior was a bug that caused very poor performance when the swapchain was promoted by DWM into Independent Flip mode. BitBlt swapchains like `D3DSWAPEFFECT_DISCARD` have been actively discouraged by Microsoft in favor of Flip swapchains since Windows 8 for improved rendering efficiency. The developer of Lossless Scaling calls GDI mode "legacy" for a reason. It is an outdated technique that is incompatible with newer D3D9Ex, D3D11, and D3D12 applications.

Mouse cursor scaling doesn't seem relevant here, because the mouse cursor is pre-encoded into the video stream by the host. It's not drawn on the client-side for scaling to be needed. In any case, I believe that Lossless Scaling can support proper mouse cursor scaling using  `IDXGIOutputDuplication::GetFramePointerShape()` or a GDI-based technique like [this](https://stackoverflow.com/questions/70553039/get-correct-cursor-image-from-windows-api).

Adding new options to Moonlight isn't free. Each new option requires translation updates, testing for each release (in all relevant combinations with other options), documentation, and code maintenance burden. It doesn't seem worth having a Windows-specific option that only works in one specific scenario (windowed v-sync off) to support a "legacy" non-default option in a third-party application.

**Comment by makedir** [comment] 2022-05-25 17:02
You could look into implementing some scale options in the future, the same as lossless scaling does. Integer/nearest neighbor would be a good start for a non blurry upscale. But could also use AMDs FSR or Nvidia scaler.

I am not happy with this change, and mostly have to stay with version 4.0.0.

**Comment by cgutman** [comment] 2022-05-28 18:49
OK, looks like we already have an issue for integer scaling support (#349), so I'll close this.

**Closed by cgutman** 2022-05-28 18:49 UTC
Labels: need more info
