### ISSUE TITLE
Stream freezes randomly since some short time

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#688] opened 2021-12-11 00:21 UTC
Not sure why this is happening, mostly since one of the last GFE updates, the stream randomly freezes and only way to make it work again is by closing Moonlight client, click the X on the stream, and then restart stream.

Any way to debug why this is happening? It just started to happen since a few weeks, maybe 1-3 weeks or so, never had this issue before.

Am on Windows 11 client, and Windows 11 server.

**Comment by cgutman** [comment] 2021-12-11 19:48
This is probably related to the issues with the R495 drivers mentioned in #682 and #677.

Try upgrading to the latest driver 497.09. If that still doesn't work, try disabling the hardware-accelerated GPU scheduling option on your host.

**Comment by makedir** [comment] 2021-12-11 19:55
Omg...thank you for the hint. You mean the option you can turn on in Windows 10/11 graphics settings? I think I have it indeed turned on both on client and server, but since some months, had no issue so far with it.

Did you report a bug report to Nvidia about it or is there any? So I should disable it on the server but can leave it on at client side?

I will try if that helps.

**Comment by HunterAhlquist** [comment] 2021-12-15 05:00
Having the same issue. Video freezes, but audio and input continues to work. Drivers are up-to-date on both sides and my client (my laptop) has Moonlight-qt set to run on the discrete GPU.
Network wise, the only thing between my desktop and laptop is a gigabit dummy switch (they're both wired, 1ms latency)

**Comment by cgutman** [comment] 2021-12-16 02:01
@HunterAhlquist did you try the solution I suggested?

**Comment by mmegm** [comment] 2021-12-16 22:47
Disabling GPU scheduled boosting in the Graphic Settings of Windows 10 works for me. No freezing or black screens anymore.

**Comment by makedir** [comment] 2021-12-16 22:50
Someone can report a bug report to Nvidia about this please.

**Comment by magcilyl** [comment] 2022-04-22 13:48
It still exists

**Comment by mmegm** [comment] 2022-04-22 13:51
> It still exists

Did you try disabling "GPU scheduled boosting" in the "Graphic Settings" of Windows 10. Its the bottom Link.
<img width="861" alt="Bildschirmfoto 2022-04-22 um 15 50 38" src="https://user-images.githubusercontent.com/4106416/164727851-008f4750-04b0-4685-a310-7a7cc276ec25.png">

**Comment by makedir** [comment] 2022-04-22 15:40
Did someone report this bug in the meantime to Nvidia?

**Comment by magcilyl** [comment] 2022-04-23 04:01
Try to disabe the hardware-accelerated GPU scheduling option. I solved this proble yesterday

> Did someone report this bug in the meantime to Nvidia?

**Comment by makedir** [comment] 2022-04-23 04:17
> Try to disabe the hardware-accelerated GPU scheduling option. I solved this proble yesterday
> 
> > Did someone report this bug in the meantime to Nvidia?

what... ? I asked, if someone reported this to Nvidia, so they fix it. Obviously we want to use hardware accelerated GPU scheduling ...

**Comment by cgutman** [comment] 2022-04-23 22:14
Yes, it's been reported and they've reproduced it in their lab.

**Comment by magcilyl** [comment] 2022-04-24 02:07
> > It still exists
> 
> Did you try disabling "GPU scheduled boosting" in the "Graphic Settings" of Windows 10. Its the bottom Link. <img alt="Bildschirmfoto 2022-04-22 um 15 50 38" width="861" src="https://user-images.githubusercontent.com/4106416/164727851-008f4750-04b0-4685-a310-7a7cc276ec25.png">

Thanks. It works!

**Comment by cgutman** [comment] 2022-05-07 19:41
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

**Closed by cgutman** 2022-05-07 19:41 UTC

**Comment by makedir** [comment] 2023-08-24 02:07
Is this bug still present? I got a new PC and installed Sunshine on it, and stream freezes randomly, not sure if it is related to this bug or something else. The option for GPU scheduling is also not there to disable anymore in Windows 11.
