### ISSUE TITLE
Mouse cursor shift when selecting texts

### ISSUE THREAD

**Issue by zycboss** [moonlight-stream/moonlight-qt#615] opened 2021-06-23 05:57 UTC
When trying to select texts from a client PC, the cursor will change appearance to a bar "I", but the actual position of the cursor is not, causing shift and inaccurate selection every time.

After toggled on local cursor display, you can see there is a small gap between real cursor and the host shows.

The real cursor position is always a little up-left than the bar "I".

See attached photos for reference.
![image](https://user-images.githubusercontent.com/29044143/123043515-f8093500-d42a-11eb-90ab-ee551af0eb85.png)
![image](https://user-images.githubusercontent.com/29044143/123043527-fb042580-d42a-11eb-848a-c981f9a2a373.png)

**Client PC details**
 - OS: Windows 10 21H1
 - Moonlight Version: v3.1.3
 - GPU: AMD Vega 8

**Server PC details**
 - OS: Windows 10 21H1
 - GeForce Experience version:  3.23.0.74
 - Nvidia GPU driver: 466.77
 - Antivirus and firewall software: NO

**Additional context**
Changing to different cursor styles on both client and server PC, will not fix this issue.
This issue will not appear on other situation, but only when texts selecting.

**Comment by zackfuchtel** [comment] 2021-08-15 08:26
I have realized this issue also with moonlight-qt 3.1.4 on a pi400 to a win11 host and newest Geforce Software.

**Comment by zycboss** [comment] 2021-08-15 12:29
> I have realized this issue also with moonlight-qt 3.1.4 on a pi400 to a win11 host and newest Geforce Software.

I also found when resizing window the cursor position will shift too, which is quite annoying.

**Comment by cgutman** [comment] 2021-08-15 16:53
This is a duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/10 (not a Moonlight bug).

NVIDIA knows about the bug and they are fixing it.

**Closed by cgutman** 2021-08-15 16:53 UTC
