### ISSUE TITLE
Streaming Problems on RTX 3050

### ISSUE THREAD

**Issue by aearley13** [moonlight-stream/moonlight-qt#747] opened 2022-03-07 03:19 UTC
Firewall has been disabled and internet hosting tool says that my PC is ready to stream over the internet. However I still cannot stream and get handshake error 60 please check your firewall/port forwarding 48000/48010

**Comment by cgutman** [comment] 2022-05-30 21:11
Duplicate of #727

**Closed by cgutman** 2022-05-30 21:11 UTC
