### ISSUE TITLE
HEVC with RTX 3090 (possibly also 3080?)

### ISSUE THREAD

**Issue by Sanazin** [moonlight-stream/moonlight-qt#447] opened 2020-09-25 20:21 UTC
Hello,

I'm using an RTX 3090 (Win 10) with latest drivers, latest Win10 update, latest moonlight (basically latest anything you can think of) and getting the error message "Your host PC GP doesn't support HEVC.." which is a bit weird. It worked fine with my GTX 1080.
My client PC is also Win10 (latest etc...) running GT 1030, but that PC is just the "receiver".
I've attached a couple of recent moonlight logs from %temp% folder and a picture of my moonlight settings. 

Any ideas?

Best regards
Sanazin

[Moonlight-1601052395.log](https://github.com/moonlight-stream/moonlight-qt/files/5285178/Moonlight-1601052395.log)
[Moonlight-1601062816.log](https://github.com/moonlight-stream/moonlight-qt/files/5285179/Moonlight-1601062816.log)
[Moonlight-1601061529.log](https://github.com/moonlight-stream/moonlight-qt/files/5285181/Moonlight-1601061529.log)
[Moonlight-1601059846.log](https://github.com/moonlight-stream/moonlight-qt/files/5285182/Moonlight-1601059846.log)
![Moonlight](https://user-images.githubusercontent.com/71903644/94312599-7a88c500-ff7d-11ea-85f8-08d1248a62f8.png)

**Comment by cgutman** [comment] 2020-09-25 21:20
Interesting. We've seen this with the GTX 1650 too. I suspect it's on Nvidia's end, but I'll need more info to confirm.

Please upload your NvStreamer logs from `C:\ProgramData\NVIDIA Corporation\NvStream`. Please also navigate to https://127.0.0.1:47989/serverinfo on your host machine and post the contents here.

**Comment by Sanazin** [comment] 2020-09-26 16:10
> Interesting. We've seen this with the GTX 1650 too. I suspect it's on Nvidia's end, but I'll need more info to confirm.
> 
> Please upload your NvStreamer logs from your host at `C:\ProgramData\NVIDIA Corporation\NvStream`. Please also navigate to http://127.0.0.1:47989/serverinfo on your host machine and post the contents here.

Attached the requested files. It looks strange indeed. In the Nvstream-log the following is printed:

_#2(D)[2020-09-25 20:45:18,999]=22:45:18={13680}<ServerMiscUtils>  Failed to find an exact match for this GPU
#3(I)[2020-09-25 20:45:18,999]=22:45:18={13680}<NvEnc10VideoEnco> Device '' does not support HEVC._

[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/5286954/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-qt/files/5286955/NvStreamerOld.log)
[Serverinfo.txt](https://github.com/moonlight-stream/moonlight-qt/files/5286956/Serverinfo.txt)

**Comment by cgutman** [comment] 2020-09-26 18:28
Yeah, it looks like Nvidia needs to update the code on their end to enable HEVC support for the new RTX 3000 cards.

```
#1(I)[2020-09-25 20:45:23,378]=22:45:23={13504}<NvEnc10VideoEnco> Device 'GeForce RTX 3090' does not support HEVC.
```

Hopefully that's already in the pipeline (and maybe why GFE 3.20.5 is in Beta longer than usual, while they spin a new build). In any case, it might be a good idea to file a bug report with Nvidia saying that GameStream HEVC isn't working on your RTX 3090 and provide those same logs on https://www.nvidia.com/en-us/support/consumer/

**Comment by Sanazin** [comment] 2020-09-26 18:53
> Yeah, it looks like Nvidia needs to update the code on their end to enable HEVC support for the new RTX 3000 cards.
> 
> ```
> #1(I)[2020-09-25 20:45:23,378]=22:45:23={13504}<NvEnc10VideoEnco> Device 'GeForce RTX 3090' does not support HEVC.
> ```
> 
> Hopefully that's already in the pipeline (and maybe why GFE 3.20.5 is in Beta longer than usual, while they spin a new build). In any case, it might be a good idea to file a bug report with Nvidia saying that GameStream HEVC isn't working on your RTX 3090 and provide those same logs on https://www.nvidia.com/en-us/support/consumer/

Thank you for your confirmation. Created an support ticket with Nvidia.
Hopefully it'll be fixed in the next release of GFE =)

**Comment by Sanazin** [comment] 2020-10-07 20:22
Nvidia has now raised the ticket to their 2nd Line so waiting for an response. Will let you know!

**Comment by lmxx1234567** [comment] 2020-11-11 03:42
> Nvidia has now raised the ticket to their 2nd Line so waiting for an response. Will let you know!

Hi @Sanazin , any progress now?

**Comment by Sanazin** [comment] 2020-11-11 06:00
> > Nvidia has now raised the ticket to their 2nd Line so waiting for an response. Will let you know!
> 
> Hi @Sanazin , any progress now?

Indeed there has been some progress. Receives this from Nvidia a few days ago and they've also confirmed this on their own GameStream forums where others have also raised this issue.

"Our quality lab was able to confirm the issue and have escalated the bug to our engineering team to investigate. We will provide a solution as soon as we can. Thank you for bring this issue to our attention."

**Comment by kayjaybees** [comment] 2020-11-11 07:08
This may explain the horrible artifacting I'm getting with my 3080 when streaming to the Shield. 
The issue isn't isolated to Moonlight. Gamestream has it too. The only way to clear it is to end the stream and start again.

**Comment by Sanazin** [comment] 2020-11-11 08:45
I was just about to inform you about the hotfix! =) Will try tonight.

**Comment by hydalisk** [comment] 2020-11-24 04:38
also in RTX3070,it show me"Your host PC GPU doesn't support HEVC..."

**Comment by MichaelRRM** [comment] 2020-11-24 11:01
Same issue for me with a RTX3070, driver 457.30. 

But I understand this is an Nvidia issue more than moonlight, I'll take it there.

**Comment by MatthieuTinnes** [comment] 2020-11-29 10:33
Same here with driver 465.12 on a RTX 3070

**Comment by lmxx1234567** [comment] 2020-11-29 14:30
Hi @MichaelRRM  @MatthieuTinnes , it doesn't seem to be an Nvidia driver issue, but GeForce Experience.

**Comment by cgutman** [comment] 2020-11-29 16:12
A fix was already posted here posted 2 weeks ago, but I will link it again: https://nvidia.custhelp.com/app/answers/detail/a_id/5106

Closing this ticket because the bug is fixed by Nvidia.

**Closed by cgutman** 2020-11-29 16:12 UTC

**Comment by wax7** [comment] 2021-06-14 13:33
Looks like the RTX3060/RTX3070 on Notebooks have this problem too...
i Opened a NVidia Incident for this.

Anybody else with this problem?
