### ISSUE TITLE
Mouse cursor point target wrong

### ISSUE THREAD

**Issue by AdamKlob** [moonlight-stream/moonlight-qt#626] opened 2021-07-20 08:21 UTC
**Describe the bug**
I'm sorry, I do not know correct terminology here.

If a mouse cursor changes to a form that 'target clicking point' is not in top left corner, it will default to top left corner, it seems that Moonlight does not follow how cursor is set up in that regard.

**Affected games**
Factorio (while using upgrade or deconstruction planners) (https://factorio.com/, demo version available)

**Other Moonlight clients**
Did not test

**Moonlight settings (please complete the following information)**
- Screen size changed to 1920x1080, other settings default

**Client PC details (please complete the following information)**

OS: Windows 10 19041.1083
Moonlight Version: 3.1.4
GPU: Nvidia GTX 1660 TI

**Server PC details (please complete the following information)**

OS: Windows 10 19043.2021
GeForce Experience version: 3.23.0.74
Nvidia GPU driver: [e.g. 471.11
Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment] 2021-07-20 13:59
Known issue with NVIDIA GameStream itself. Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/10

**Closed by cgutman** 2021-07-20 13:59 UTC
