### ISSUE TITLE
"-platform wayland" switch problem if i edit .desktop file.

### ISSUE THREAD

**Issue by vampywiz17** [moonlight-stream/moonlight-qt#228] opened 2019-05-08 14:03 UTC
Hello there,

I use Fedora 30 and update latest Moonlight QT with flatpak.

I edit the .desktop file with moonlight:

```
Desktop Entry]
Name=Moonlight
Comment=Stream games from your NVIDIA GameStream-enabled PC
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=moonlight com.moonlight_stream.Moonlight -platform wayland
Icon=com.moonlight_stream.Moonlight
Terminal=false
Type=Application
Categories=Qt;Game;
Keywords=nvidia;gamestream;stream;
X-Flatpak=com.moonlight_stream.Moonlight
```

But if i start a app (like steam) it crash. But if i start moonlight with command line `flatpak run com.moonlight_stream.Moonlight -platform wayland 
` it working without problem. 

Now i use the program, if i start it in terminal, but the "icon way" is comfortable..

**Comment by vampywiz17** [comment] 2019-05-08 14:44
Unfortunately it happened with terminal mode.... i think the problem that start stream, the app cant recognise the window correctly (no border, no header, etc...)

**Comment by cgutman** [comment] 2019-05-09 02:28
Can you post the output from attempting to run Moonlight?

**Comment by vampywiz17** [comment] 2019-05-09 09:49
```
[snorbert@vamp-notebook ~]$ flatpak run com.moonlight_stream.Moonlight -platform wayland
00:00:00 - Qt Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
00:00:00 - Qt Warning: QSocketNotifier: Can only be used with threads started with QThread
00:00:00 - SDL Info (0): Detected Wayland. Performance may be worse than X11.
00:00:00 - Qt Debug: Using Wayland-EGL
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:00 - SDL Info (0): V-sync enabled
00:00:00 - SDL Info (0): Initialized VAAPI 1.4
00:00:00 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x32315659 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x30323449 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x3231564e -> nv12.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x32595559 -> yuyv422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x59565955 -> uyvy422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x48323234 -> yuv422p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x58424752 -> rgb0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x58524742 -> bgr0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Format 0x30313050 -> p010le.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] VAAPI driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x563e3d629c40] Driver not found in known nonstandard list, using standard behaviour.
00:00:00 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:00 - SDL Info (0): Using VAAPI accelerated renderer on Wayland
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Format vaapi_vld chosen by get_format().
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Format vaapi_vld requires hwaccel initialisation.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Considering format 0x3231564e -> nv12.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000000.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Direct mapping disabled: derived image format 3231564e does not match expected format 32315659.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000001.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000002.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000003.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000004.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000005.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000006.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000007.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000008.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000009.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000a.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000b.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000c.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000d.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000e.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x400000f.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000010.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000011.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000012.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x563e3d81ff00] Created surface 0x4000013.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Considering format 0x3231564e -> nv12.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Decode context initialised: 0x1000000/0x2000000.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Reinit context to 1280x720, pix_fmt: vaapi_vld
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Param buffer (type 0, 672 bytes) is 0x8000000.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Param buffer (type 1, 240 bytes) is 0x8000001.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 0 param buffer (3128 bytes) is 0x8000002.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 0 data buffer (75 bytes) is 0x8000003.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 1 param buffer (3128 bytes) is 0x8000004.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 1 data buffer (80 bytes) is 0x8000005.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 2 param buffer (3128 bytes) is 0x8000006.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 2 data buffer (85 bytes) is 0x8000007.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 3 param buffer (3128 bytes) is 0x8000008.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Slice 3 data buffer (97 bytes) is 0x8000009.
00:00:00 - FFmpeg: [h264 @ 0x563e3d7fe840] Decode to surface 0x4000013.
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:00 - Qt Debug: Using the 'xdg-shell' shell integration
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "0.10.1"
00:00:10 - Qt Info: "VAMP-PC" is now offline
00:00:30 - Qt Info: "VAMP-PC" is now online at "192.168.31.102"
00:00:41 - Qt Info: Server GPU: "GeForce GTX 1060 3GB"
00:00:41 - Qt Info: Server GFE version: "3.18.0.102"
00:00:41 - SDL Info (0): Encoder configured for 4 slices per frame
00:00:41 - SDL Info (0): Video bitrate: 10000 kbps
00:00:41 - SDL Info (0): Audio configuration: 0
00:00:41 - SDL Info (0): V-sync enabled
00:00:41 - SDL Info (0): Initialized VAAPI 1.4
00:00:41 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x32315659 -> yuv420p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x30323449 -> yuv420p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x3231564e -> nv12.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x32595559 -> yuyv422.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x59565955 -> uyvy422.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x48323234 -> yuv422p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x58424752 -> rgb0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x58524742 -> bgr0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Format 0x30313050 -> p010le.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] VAAPI driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f86ef00] Driver not found in known nonstandard list, using standard behaviour.
00:00:41 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:41 - SDL Info (0): Using VAAPI accelerated renderer on Wayland
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Decoding VPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Main profile bitstream
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Decoding SPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Main profile bitstream
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Decoding VUI
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Decoding PPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Format vaapi_vld chosen by get_format().
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Format vaapi_vld requires hwaccel initialisation.
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] No support for codec hevc profile 1.
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Format vaapi_vld not usable, retrying get_format() without it.
00:00:41 - FFmpeg: [hevc @ 0x563e40f0a1c0] Error parsing NAL unit #3.
00:00:41 - SDL Warn (0): Test decode failed: A művelet nem engedélyezett
Failed to open VDPAU backend libvdpau_nvidia.so: nem nyitható meg a megosztott objektumfájl: Nincs ilyen fájl vagy könyvtár
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f7d1000] VDPAU device creation on X11 display :99.0 failed.
00:00:41 - SDL Error (0): Failed to create VDPAU context: -1313558101
00:00:41 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:41 - SDL Info (0): Using SDL renderer
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Decoding VPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Main profile bitstream
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Decoding SPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Main profile bitstream
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Decoding VUI
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Decoding PPS
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Format yuv420p chosen by get_format().
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Output frame with POC 3.
00:00:41 - FFmpeg: [hevc @ 0x563e40f29140] Decoded frame with POC 3.
00:00:41 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:41 - SDL Info (0): V-sync enabled
00:00:41 - SDL Info (0): Initialized VAAPI 1.4
00:00:41 - SDL Info (0): Driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x32315659 -> yuv420p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x30323449 -> yuv420p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x3231564e -> nv12.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x32595559 -> yuyv422.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x59565955 -> uyvy422.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x48323234 -> yuv422p.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x58424752 -> rgb0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x58524742 -> bgr0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Format 0x30313050 -> p010le.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] VAAPI driver: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0.
00:00:41 - FFmpeg: [AVHWDeviceContext @ 0x563e3f727100] Driver not found in known nonstandard list, using standard behaviour.
00:00:41 - Qt Info: Found "ModeSeven.ttf" at ":/data/ModeSeven.ttf"
00:00:41 - SDL Info (0): Using VAAPI accelerated renderer on Wayland
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Format vaapi_vld chosen by get_format().
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Format vaapi_vld requires hwaccel initialisation.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Considering format 0x3231564e -> nv12.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000000.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Direct mapping disabled: derived image format 3231564e does not match expected format 32315659.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000001.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000002.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000003.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000004.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000005.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000006.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000007.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000008.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000009.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000a.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000b.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000c.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000d.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000e.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x400000f.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000010.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000011.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000012.
00:00:41 - FFmpeg: [AVHWFramesContext @ 0x563e40f0b900] Created surface 0x4000013.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Considering format 0x3231564e -> nv12.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Picked nv12 (0x3231564e) as best match for yuv420p.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Decode context initialised: 0x1000000/0x2000000.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Reinit context to 1280x720, pix_fmt: vaapi_vld
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Param buffer (type 0, 672 bytes) is 0x8000000.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Param buffer (type 1, 240 bytes) is 0x8000001.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 0 param buffer (3128 bytes) is 0x8000002.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 0 data buffer (75 bytes) is 0x8000003.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 1 param buffer (3128 bytes) is 0x8000004.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 1 data buffer (80 bytes) is 0x8000005.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 2 param buffer (3128 bytes) is 0x8000006.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 2 data buffer (85 bytes) is 0x8000007.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 3 param buffer (3128 bytes) is 0x8000008.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Slice 3 data buffer (97 bytes) is 0x8000009.
00:00:41 - FFmpeg: [h264 @ 0x563e40f65140] Decode to surface 0x4000013.
00:00:41 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:41 - SDL Info (0): Audio backend: PulseAudio
00:00:41 - SDL Info (0): Selected audio device: Belső hangforrás Analóg sztereó
00:00:41 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:41 - SDL Info (0): Audio buffer size: 10 packets
00:00:41 - SDL Info (0): Audio latency: 0,030505
00:00:41 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:41 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:43 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:43 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:43 - SDL Info (0): Found host supported resolution: 1280x720
00:00:43 - Qt Info: Executing request: "https://192.168.31.102:47984/launch?uniqueid=0123456789ABCDEF&uuid=66f4d4bd9d0e44bcaa40290947cf3819&appid=1782064886&mode=1280x720x60&additionalStates=1&sops=1&rikey=16a2619fa7161c193d04e4631086a60a&rikeyid=707311212&localAudioPlayMode=0&surroundAudioInfo=196610&remoteControllersBitmap=0&gcmap=0"
00:00:47 - SDL Info (0): Initializing platform...
00:00:47 - SDL Info (0): done
00:00:47 - SDL Info (0): Resolving host name...
00:00:47 - SDL Info (0): done
00:00:47 - SDL Info (0): Starting RTSP handshake...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Initializing control stream...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Initializing video stream...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Initializing audio stream...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Initializing input stream...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Starting control stream...
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Starting video stream...
00:00:58 - SDL Info (0): Video stream is 1280x720x60 (format 0x1)
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Starting audio stream...
00:00:58 - SDL Info (0): Audio backend: PulseAudio
00:00:58 - SDL Info (0): Selected audio device: Belső hangforrás Analóg sztereó
00:00:58 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:58 - SDL Info (0): Audio buffer size: 10 packets
00:00:58 - SDL Info (0): Audio stream has 2 channels
00:00:58 - SDL Info (0): done
00:00:58 - SDL Info (0): Starting input stream...
00:00:58 - SDL Info (0): done

```

**Comment by vampywiz17** [comment] 2019-05-21 09:29
Any step is this issue? Now in install the new version, but i get the same problem.

**Comment by cgutman** [comment] 2019-05-25 16:54
I'm not sure. I can't reproduce this on my laptop running Fedora 30 and Wayland. I developed the Wayland support on that machine, so I should have seen the issue.

**Comment by cgutman** [comment] 2019-06-15 20:49
I think this is a bug in the version of Mesa that's currently in the KDE 5.12 Flatpak runtime. My host is running 19.0.6 and the crash doesn't happen, but it does on 18.3.6 which is the current version in org.kde.Platform//5.12.

It looks like the FreeDesktop SDK has updated to 19.0.6 but it hasn't trickled down to org.kde.Platform yet. It should get picked up in the next SDK build.

**Comment by cgutman** [comment] 2019-06-20 00:30
Fixed by the org.kde.Platform 5.12.4 update.

`flatpak update` to get the fix.

**Closed by cgutman** 2019-06-20 00:30 UTC
