### ISSUE TITLE
Is there any tune for speeding up initialising connection?

### ISSUE THREAD

**Issue by Kobain-Seo** [moonlight-stream/moonlight-qt#1132] opened 2023-11-30 07:19 UTC
Hi, Moonlight is great for me to play game remotely.
But when i connect to sunshine server, it takes about 20 seconds. is there any way to reduce that time?
I don't know what is going on when 'starting desktop'.

**Comment by krillme** [comment] 2023-12-01 00:11
I have noticed this becoming a problem only fairly recently, maybe a month or two. I wonder if this is caused by changes in Moonlight or Sunshine?

**Comment by Kobain-Seo** [comment] 2023-12-01 00:32
> I have noticed this becoming a problem only fairly recently, maybe a month or two. I wonder if this is caused by changes in Moonlight or Sunshine?

i tested NVIDIA Gamestream with moonlight and it was faster than sunshine.

**Comment by cgutman** [comment] 2024-02-17 04:44
This is fixed in Sunshine [nightly builds](https://github.com/LizardByte/Sunshine/releases/nightly-dev).

**Closed by cgutman** 2024-02-17 04:44 UTC
