### ISSUE TITLE
Moonlight starts on primary display instead on secondary (Mac OS)

### ISSUE THREAD

**Issue by witchcraftsman** [moonlight-stream/moonlight-qt#854] opened 2022-08-21 16:11 UTC
**Describe the bug**
With external monitor connected and moonlight started on it, streaming session is opened on laptop's display.

**Steps to reproduce**
Connect external monitor, Mac OS assigns Desktop 2 space for it (seen with F3 key)
Launch moonlight while focused on Desktop 2 so it launches in it

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
N/A

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Not really, except for resolution, bitrate and enabling HDR (tried disabling thought)
- If so, which settings have been changed? Above
- Does the problem still occur after reverting settings back to default? Is there such a button in UI?

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly? No
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Mac OS 12.5.1
 - Moonlight Version: [e.g. v0.9.0] 4.1.0
 - GPU: [e.g. Intel HD Graphics 520] M1 Pro

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809] Windows 10 21H2 19044.1889
 - GeForce Experience version: [e.g. 3.16.0.140] 3.25.1.27
 - Nvidia GPU driver: [e.g. 417.35] 516.94
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall] Disabled

**Moonlight Logs [(please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`
[Moonlight-1661096902.log](https://github.com/moonlight-stream/moonlight-qt/files/9389527/Moonlight-1661096902.log)

**Additional context**
Haven't used my MacBook with external monitor for quite some time, and I haven't had this issue before, so moonlight clight was able to run streaming session on attached monitor.

**Comment by cgutman** [comment] 2022-08-22 02:15
Duplicate of #813

**Closed by cgutman** 2022-08-22 02:15 UTC
