### ISSUE TITLE
17-50%+ frames dropped by your network connection on macOS

### ISSUE THREAD

**Issue by j9ac9k** [moonlight-stream/moonlight-qt#490] opened 2020-12-26 07:06 UTC
Hello moonlight maintainers.

**Describe the bug**
While streaming an idle desktop to a macOS client, and having the debug overlay, It is showing 30-50%+ frames dropped by your network connection values.

Some things I feel appropriate to point out right away.

1. The gamestream host is on my LAN
2. This is over a wired connection (using a thunderbolt3 docking station) with WiFi disabled (and Location services disabled)
3. Running moonlight on a windows (XPS 15) laptop, connected to the same docking station, and to the same host shows 0% frames dropped by your network connection

**Steps to reproduce**
On macOS connect to a client over a wired (and likely wireless) connection, and observe the debug overlay statistics. 

Moving my mouse _appeared_ to make things work, while letting my mouse sit idle, the frame drop rate would usually hover around 28%

**Screenshots**
![Screen Shot 2020-12-25 at 10 56 17 PM](https://user-images.githubusercontent.com/646398/103146898-8d3da200-4704-11eb-9bc6-e950e18787b6.png)

**Affected games**
N/A?  I was just streaming the desktop

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?

This does _not_ occur on the windows client.

**Moonlight settings (please complete the following information)**
I do not recall what the default settings are, but here is a screenshot of the setting window:

![image](https://user-images.githubusercontent.com/646398/103146930-e9082b00-4704-11eb-8141-afc3ee72fdd0.png)

**Client PC details (please complete the following information)**
 - OS: macOS 11 (10.16)
 - Moonlight Version: v2.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 20H2
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 460.89 (Nvidia RTX / Quadro Desktop and Notebook Driver)
 
**Moonlight Logs (please attach)**
[Moonlight-1608963734.log](https://github.com/moonlight-stream/moonlight-qt/files/5742790/Moonlight-1608963734.log)

**Additional context**
I have attempted toggling V-Sync enable on/off as well as adjusting the bit-rate significantly higher than what is in the screenshot with no change in behavior.

Only other thing I want to say is you all make an amazing tool, thank you for your work.

**Comment by cgutman** [comment] 2020-12-26 16:44
The overlay report is misleading here. The decoder or renderer is so completely backed up that it can't even ingest frames fast enough to prevent them from being dropped on the receive-side due to exhausting receive buffers. This makes it look like a network problem, when it isn't.

Fortunately, the log tells the true story:
```
00:24:54 - SDL Info (0): Video decode unit queue overflow
00:24:54 - SDL Info (0): IDR frame request sent
00:24:54 - SDL Info (0): Video decode unit queue overflow
00:24:54 - SDL Info (0): IDR frame request sent
00:24:55 - SDL Info (0): Video decode unit queue overflow
00:24:55 - SDL Info (0): IDR frame request sent
00:24:56 - SDL Info (0): Video decode unit queue overflow
```

The backup to exactly 30 FPS is strange, and and implies something on the system is only operating at 30 Hz. Is your display at 30 Hz?

What is the exact model of your Mac client? If it's older, decoder performance limitations could prevent it from achieving good performance at 3840x1600.

**Comment by j9ac9k** [comment] 2020-12-26 16:59
Nice detective work, thanks for pointing that out!

The client is a new(ish) model laptop:

![image](https://user-images.githubusercontent.com/646398/103155858-22b65180-4758-11eb-9f69-995dccf67248.png)

I was running on an external display is an AW3821DW set to run at 120 Hz.

![image](https://user-images.githubusercontent.com/646398/103155887-68731a00-4758-11eb-934f-abb7a3e7986b.png)

While the docking station does support DisplayPort 1.4, I do have a USB-C/DP adapter I could try using in its place.

**Comment by j9ac9k** [comment] 2020-12-26 17:28
I disconnected from the docking station and just ran moonlight using the laptop display and over the WiFi.

Things were remarkably better (closer to 60 Hz display) but still showing a significant percentage of dropped frames due to the network connection (I get this is misleading, and not that is actually happening.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/646398/103156345-a07c5c00-475c-11eb-963b-8861214a8a7d.png)

Here is a log:

[Moonlight-1609003449.log](https://github.com/moonlight-stream/moonlight-qt/files/5743448/Moonlight-1609003449.log)

**Comment by cgutman** [comment] 2020-12-26 18:27
Hah, as luck would have it, I have that exact MacBook Pro too. I can reproduce the issue here.

I think this is a severe performance regression in Big Sur, since I'm almost positive I streamed at native resolution on this Mac before. The video decoder in the Intel Ice Lake chips is rated to handle up to 8K HEVC streams, so the hardware itself is not the limitation.

I will try to see what's going on and report it to Apple if needed. In the meantime, you can try using the "Force software decoding" decoder option, or stream at 1080p.

**Comment by j9ac9k** [comment] 2020-12-26 18:36
> Hah, as luck would have it, I have that exact MacBook Pro too. I can reproduce the issue here.
> 
> I think this is a severe performance regression in Big Sur, since I'm almost positive I streamed at native resolution on this Mac before. The video decoder in the Intel Ice Lake chips is rated to handle up to 8K HEVC streams, so the hardware itself is not the limitation.
> 
> I will try to see what's going on and report it to Apple if needed. In the meantime, you can try using the "Force software decoding" decoder option, or stream at 1080p.

What luck! 

Let me know if I can provide any additional information (especially related to the external display).

**Comment by j9ac9k** [comment] 2020-12-26 19:50
> I will try to see what's going on and report it to Apple if needed. In the meantime, you can try using the "Force software decoding" decoder option, or stream at 1080p.

Confirming force software decoding is lowering decode times from 10-20ms to ~1-2ms (on the native display, haven't tried with the external ultrawide display yet)

**Comment by j9ac9k** [comment] 2020-12-26 23:10
Decided to experiment with some other tools to see how they perform; looks like decode time on Parsec is similar

![Screen Shot 2020-12-26 at 3 04 50 PM](https://user-images.githubusercontent.com/646398/103160595-24017180-478c-11eb-8295-bade19f664b3.png)

Also to relay some info from our chat in Discord, looks like `VTDecoderXPCService _dispatch_worker_thread` is getting deprioritized.

![image](https://user-images.githubusercontent.com/646398/103160619-75a9fc00-478c-11eb-9046-49480f21c2ff.png)

**Comment by cgutman** [comment] 2020-12-27 16:35
This turned out to be related to setting `kCVPixelBufferIOSurfaceOpenGLTextureCompatibilityKey` on the pixel buffers in FFmpeg, which apparently causes a massive performance impact on Big Sur.

I fixed it in our FFmpeg build with https://github.com/cgutman/moonlight-deps/commit/4c2815b5f2045ef0e8b098ed2fa8c4f9c1f5cd77 and landed the new binaries in the the source tree with https://github.com/moonlight-stream/moonlight-qt/commit/c923d643b9180484b2a4b48d7e18c3342ff20501

**Closed by cgutman** 2020-12-27 16:35 UTC
