### ISSUE TITLE
Macros can not be used to emulate keyboard shortcuts on macOS 14.1.1

### ISSUE THREAD

**Issue by lukewin-es** [moonlight-stream/moonlight-qt#1149] opened 2024-01-03 20:52 UTC
Running macOS 14.1.1 on a 2023 MacBook Pro M2 Pro

I am attempting to create macros that emulate the shortcuts provided by moonlight (shift+ctrl+opt+z). 

Whenever these keystrokes are applied not through the keyboard the result is the same; Moonlight passes the Z key through to the streamed computer and leaves the modifiers behind to run on the system itself.

This can be reproduced with AppleScripts, any macro software for peripherals (e.g. Corsair, Logitech, Loupedeck, Streamdeck, etc.)

**Comment by cgutman** [comment] 2024-02-17 23:00
Duplicate of #1091

**Closed by cgutman** 2024-02-17 23:00 UTC
