### ISSUE TITLE
Unable to pair my pc.

### ISSUE THREAD

**Issue by Ayting69** [moonlight-stream/moonlight-qt#703] opened 2022-01-06 13:28 UTC
Hello.

I have the locked icon on my stream moonlight app, i click on it then i get the pin code, and the shield pop up comes out on my host pc, so i enter the pin code and then i get an error message "pc not paired" (it's not exactly that my moonlight is in french)

i tried multiple times, it doesn't work.

**Comment by Klauensprung** [comment] 2022-01-07 07:48
Having the same problem but I get error 4 after entering the pair code. The computers are on the same network and can see each other. After entering the pair code it takes some time and shows 'request timed out (error 4)'

![image](https://user-images.githubusercontent.com/36606771/148510156-890c3205-fedc-47c8-a9c7-48431a120070.png)

**Comment by Ayting69** [comment] 2022-01-07 11:15
I solved the issue by uninstalling  moonlight and internet hosting tool, uninstalling my nvidia drivers with DDU and windows update disabled, and then i installed nvidia drivers and moonlight & internet hosting tool, and it work.  

Weird.

**Comment by Ayting69** [comment] 2022-04-26 08:26
I still have the same issue today, i will try to do the same thing than before but it NEED TO BE FIXED.

**Comment by loposk** [comment] 2022-05-28 11:51
+1 same problem

**Comment by Ayting69** [comment] 2022-05-28 13:33
I've founded a fix

use parsec


Way better ans if you have an issue, the devs answers you

**Comment by cgutman** [comment] 2022-05-28 18:21
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30

**Closed by cgutman** 2022-05-28 18:21 UTC

**Comment by Klauensprung** [comment] 2022-05-30 17:45
> Duplicate of [moonlight-stream/nvidia-gamestream-issues#30](https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30)

No duplicate, problem still persists and has nothing to do with my non latin username..
Installing old drivers isn't a fix and besides it also does not solve this problem.

**Comment by cgutman** [comment] 2022-05-30 20:30
> No duplicate, problem still persists and has nothing to do the windows username.

Perhaps not for you, but your issue ("request timed out") is not the same as OP's ("PC not paired").

> Installing old drivers isn't a fix and besides it also does not solve this problem.

A connection timeout is likely a network or host-side issue, but I can investigate your issue further if you file a new issue for it (and fill out the issue template with details).

**Comment by robertotucci** [comment] 2022-11-06 01:45
any news? same problem here... :(

**Comment by Ayting69** [comment] 2022-11-06 09:59
> 

No fix

My best advice : give up this 😀 called "Moonlight" and use soft which devs who Cares about their users like Parsec.

**Comment by cgutman** [comment] 2022-11-06 23:49
Please open a new ticket with logs if you continue to experience pairing issues. Each issue must be debugged independently.

As I've mentioned in a prior comment, this is an unofficial Nvidia GameStream client created by volunteers that connects to official Nvidia software (GeForce Experience). We can do our best to investigate if it's a problem on our end, but expecting commercial-level support from a community of folks doing this in their free time is probably not reasonable.

You may also try the open-source Sunshine hosting software as a replacement for GeForce Experience.
