### ISSUE TITLE
Unable to pair MacOS client (3.2.0) with Windows Host

### ISSUE THREAD

**Issue by kristoffermads** [moonlight-stream/moonlight-qt#738] opened 2022-02-21 14:49 UTC
**Describe the bug**
My setup is this: I have 1 host computer (Windows) and two Clients (Imac and Macbook). I reinstalled my iMac recently and the problems started. My Macbook can connect to the Host computer just fine - it has an older pairing. The problem is that the iMac cannot get past the pincode verification. I have tried removing the plist file before athorizing with the pincode. I have tried "remove all devices" from GFE Shield - and I have tried to reinstall GFE itself. 

**Steps to reproduce**
 - Start Moonlight
 - Click Host computer (locked icon)
 - Enter Pin-code from Moonlight, into Host Computer
 - Host Computer remains unlock OR is briefly unlocked and then locked again.

**Other Moonlight clients**
This issue also occurs on IOS client - I get the error "connection interrupted / The client is not authorized. Certificate  verification failed".

**Moonlight settings (please complete the following information)**
No settings have been adjusted - fresh install of Moonlight

**Client PC details (please complete the following information)**
 - OS: 

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.25.0.84
 - GPU: GTX 970
 - Nvidia GPU driver: 511.79
 - Antivirus and firewall software: None / Windows Defender

**Moonlight Logs (please attach)**

00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Info: No translation available for  "da_DK"
00:00:00 - Qt Warning: Populating font family aliases took 220 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/Users/username/Library/Caches/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 61 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
00:00:01 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] Format videotoolbox_vld chosen by get_format().
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] Format videotoolbox_vld requires hwaccel initialisation.
00:00:01 - FFmpeg: [h264 @ 0x7fa0bb8e8200] Reinit context to 1280x720, pix_fmt: videotoolbox_vld
00:00:01 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:01 - Qt Warning: QQmlEngine::setContextForObject(): Object already has a QQmlContext
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at "/Users/username/Library/Caches/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 61 new gamepad mappings
00:00:01 - Qt Debug: Current Moonlight version: "3.2.0"
00:00:01 - Qt Info: Gamepad mappings are up to date
00:00:01 - Qt Info: Latest supported GFE server: "99.99.99.99"
00:00:01 - Qt Debug: Found update manifest match for current platform
00:00:01 - Qt Debug: Latest version of Moonlight for this platform is: "3.2.0"
00:00:01 - Qt Debug: Update manifest version equal to current version
00:00:01 - Qt Info: Discovered mDNS host: "DESKTOP-BAVI6AI.local."
00:00:01 - Qt Info: Resolved "DESKTOP-BAVI6AI.local." to QHostAddress("10.0.1.152")
00:00:01 - Qt Info: Resolved "DESKTOP-BAVI6AI.local." to QHostAddress("fe80::b5f9:d23f:dd25:ce7")
00:00:01 - Qt Info: "DESKTOP-BAVI6AI" is now online at "10.0.1.152:47989"
00:00:03 - Qt Info: Processing new PC at "10.0.1.152:47989" from mDNS with IPv6 address "<NULL>"
00:00:03 - Qt Info: Executing request: "http://10.0.1.152:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=f393f5f1064b416cba9a501376699cfa"
00:00:03 - Qt Info: Executing request: "https://10.0.1.152:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=80fb03dda0ff445eba1aad85fd72f946"
00:00:03 - Qt Info: Executing request: "http://10.0.1.152:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=4357314c19af47908d304a62f020d848"
00:00:08 - Qt Info: Pairing with server generation: 7
00:00:08 - Qt Info: Executing request: "http://10.0.1.152:47989/pair?uniqueid=0123456789ABCDEF&uuid=0fdf4301b3cc4d179a5e947626b33506&devicename=roth&updateState=1&phrase=getservercert&salt=ef011074159c43b9ac21b882945847b4&clientcert=2d2d2d2d2d424547494e2043455254494649434154452d2d2d2d2d0a4d494943767a43434161656741774942416749424144414e42676b71686b694739773042415173464144416a4d53457748775944565151444442684f566b6c450a53554567523246745a564e30636d56686253424462476c6c626e51774868634e4d6a49774d6a45334d544d794e7a51795768634e4e4449774d6a45794d544d790a4e7a5179576a416a4d53457748775944565151444442684f566b6c4553554567523246745a564e30636d56686253424462476c6c626e5177676745694d4130470a4353714753496233445145424151554141344942447741776767454b416f494241514449567574714d6c4a696c46686e4937674b557a3456576f7377716951700a566f77494f70784176553651727570666b737469564b375251694b43594b7542682f6252513575796e4b55476e7438354153577a686a4e616d6477454f4a56780a626f2b4d5533357638466348304961637268316f4f473868427579596a6348794e65616f524252542b7930334b374967326e6768654e6d597879647a6b5365540a746b563567497846584276756a36324346386479476f4a376b2b51736e4c5076346b4956416759446c4f484534734864474e42453845506b587a4c4b5a564f570a6157793154582f66432f79747537514d55462f37374c677a777833426a487637466b7954716e7570325a44432b423354776e6e506568503633576a34355a514b0a656f584f526e3041334c44616576686d7a503766753564594c6b66514b384b2f47434f416576744a7a666a704b344446652b6b6e51764a3341674d42414145770a4451594a4b6f5a496876634e4151454c425141446767454241456835634e4d5a5a58525161414355687846587a6235366a4a374669446f74623756557832622f0a377a4c78784577582f3742767158506d39666a596b764b6458746f4e7167434c355831633035794f446b6131313063455245437976476f56397153496f5a75730a3449454152624d333634774c4471432b72596e7a3253313778366c316653684f34307055444475356f48764d56754b6b6d5976726867444e6172322f2f5332700a526241525a6c746d4852424e6965705052786b4e6f57664d6d70434c7143764a4f6d57755547454d6152476c532b526b424579703456744447417458334e6d6b0a5a454c72536c7632677030343161653367564c796a597038717449366c77307042774f72714a6d4b6e6b6d77736169417331512b536a4c4830455855376777410a4f6e42786361614a723772653439674d694a49345341516a4b6959566f414638716467694f4a4844494166736f33513d0a2d2d2d2d2d454e442043455254494649434154452d2d2d2d2d0a"
00:00:23 - Qt Info: Executing request: "http://10.0.1.152:47989/pair?uniqueid=0123456789ABCDEF&uuid=263b9b1499744ee4b028a6aaad3283e7&devicename=roth&updateState=1&clientchallenge=2a37770f057b96bc42f4c2e5bc563e5f"
00:00:23 - Qt Info: Executing request: "http://10.0.1.152:47989/pair?uniqueid=0123456789ABCDEF&uuid=fbd38f3322c540ada0f50b20f19d3971&devicename=roth&updateState=1&serverchallengeresp=12c3c6c96cea744589b27c9b85e1899e875f18b3f765aaaa367311fe88cdf184"
00:00:24 - Qt Info: Executing request: "http://10.0.1.152:47989/pair?uniqueid=0123456789ABCDEF&uuid=3384629304a84cf0b85c322ac9fb0e71&devicename=roth&updateState=1&clientpairingsecret=ea4b686a1a3596092421712b27e580cc4ba0f15fa0b1c2186506d8da3da825ab4767fe4770fd927c3a5f99bf6d5ec1261c215459728ccd5ac37de474ac9aa06b3c58bc400b82f0ff43797d87d240ef657ce9d42074cae61dc87bdeb120c57ec0976442687587eca9e122a450d3e70bd5dbbba933d50a28ec796a6c01e7966933c6b389f304a5a893a6955f7ef4e5ebd51ecff62c0680dcdfaded2c1754994fd4c7500842a893cb5caed6a7e65315c6e7a1cc8692e0483adabdf1af27ab7493d83fb124e81359226d524fff308b97e70eabf9c0c6ce20e5272be2302202f0b145c6dee688c904e0325201ba738b977871249363669c189060a49a13d4d31af6fa0b6ba4418d23804c256106faca599bc8"
00:00:24 - Qt Info: Executing request: "https://10.0.1.152:47984/pair?uniqueid=0123456789ABCDEF&uuid=5e9d2240f4e448abbb4f743dd8cdf9be&devicename=roth&updateState=1&phrase=pairchallenge"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=c1f345840dbb459095de33e0c694eff6&appid=1073206070&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=ace495ffb67b4fdf9fa9d4cff1a9af31&appid=8712496&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=12828d707335431abd2af3462319c22a&appid=581251398&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=0d22edb078814203bb20476fba3c9dc3&appid=2113120640&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=fca5c2fb4197497888a7956cd2de92d8&appid=1073206070&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=f03c11ef67dc4422a7ae880db60f4681&appid=8712496&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=ad2ff5b9348e42f3bf50a6d1787a36f5&appid=581251398&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=4bc309bb7b414a59bee6e953d14ed482&appid=2113120640&AssetType=2&AssetIdx=0"
00:00:26 - Qt Info: Executing request: "https://10.0.1.152:47984/appasset?uniqueid=0123456789ABCDEF&uuid=6933c146d951453e9b788363848dbc21&appid=1088017781&AssetType=2&AssetIdx=0"

**Comment by jveronese** [comment] 2022-02-22 19:46
Currently facing the same issue on MacOS and Ubuntu

**Comment by germanyague** [comment] 2022-02-25 20:52
Same Here: 

Client PC details (please complete the following information)

OS: iOS and ipadOS 15.3.1, MacOS 12.2.1
Server PC details (please complete the following information)

OS: Windows 11
GeForce Experience version: 3.25.0.84
GPU: RTX 2070 SUPER
Nvidia GPU driver: 511.79
Antivirus and firewall software: None / Windows Defender



00:00:00 - SDL Info (0): Compiled with SDL 2.0.21
00:00:00 - SDL Info (0): Running with SDL 2.0.21
00:00:00 - Qt Info: Successfully loaded translation for  "es_ES"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/Users/germanyague/Library/Caches/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 61 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x11f138200] Format videotoolbox_vld chosen by get_format().
00:00:00 - FFmpeg: [h264 @ 0x11f138200] Format videotoolbox_vld requires hwaccel initialisation.
00:00:00 - FFmpeg: [h264 @ 0x11f138200] Reinit context to 1280x720, pix_fmt: videotoolbox_vld
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:00 - Qt Warning: QQmlEngine::setContextForObject(): Object already has a QQmlContext
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/Users/germanyague/Library/Caches/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 61 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "3.2.0"
00:00:00 - Qt Info: Latest supported GFE server: "99.99.99.99"
00:00:00 - Qt Debug: Found update manifest match for current platform
00:00:00 - Qt Debug: Latest version of Moonlight for this platform is: "3.2.0"
00:00:00 - Qt Debug: Update manifest version equal to current version
00:00:00 - Qt Info: Gamepad mappings are up to date
00:00:00 - Qt Info: "GERMAN-ROG" is now online at "192.168.0.125:47989"
00:00:01 - Qt Info: Pairing with server generation: 7
00:00:01 - Qt Info: Executing request: "http://192.168.0.125:47989/pair?uniqueid=0123456789ABCDEF&uuid=8a5adf3580c0428c8e5e2eba8ee7c327&devicename=roth&updateState=1&phrase=getservercert&salt=14586fa16d29250949c33b2e799dc716&clientcert=2d2d2d2d2d424547494e2043455254494649434154452d2d2d2d2d0a4d494943767a43434161656741774942416749424144414e42676b71686b694739773042415173464144416a4d53457748775944565151444442684f566b6c450a53554567523246745a564e30636d56686253424462476c6c626e51774868634e4d6a49774d6a49314d6a417a4d6a4d325768634e4e4449774d6a49774d6a417a0a4d6a4d32576a416a4d53457748775944565151444442684f566b6c4553554567523246745a564e30636d56686253424462476c6c626e5177676745694d4130470a4353714753496233445145424151554141344942447741776767454b416f49424151437431727257454d756a4331315363454e496a58414561444b4b354c34430a724437687147414e584148316a4f5453682f3336395244517a6e45737232716f456c38746870307a6c425761612f39634c3150455a596f43456d766b7a6a77720a3049526f63774f66465a7a756c32572f38504e734433644665625a6e5a50544157424342715846436a446d627a773833514144556545795250563450587a304c0a713333762b6e58556a5353732f596b73576c45486c376f615872717458696f455131777a693936473272764d51626a524545485547435a3670744741364a76650a306970514a4f64754131584d57454f666a75667478434171715251506b6b497734462b4b71414b50333174384257555466444f50537767676366513276566a790a39687646447142696b38694f57764d4b6e473545362b4b313550652b534d44465753532b4a6870766a456a34514e2f662b716e7438734a3541674d42414145770a4451594a4b6f5a496876634e4151454c4251414467674542414a6452743133494d756c5032796c6a77306543354437392b4b71706a64623873433935446e6e740a7036476a3343533761354d486f6250343846424257636e4f6a337a71712f642b3151414b4b514147453133794762354475727368357954354259384b576475430a385a58346e6f4c32474e514777754f63412b785a3157756168456f766d587a6c4769344a4b5335426864396f54347664754a443846444c49685443744f56442f0a31316555644e465665476443566a384b2f43337a6c51674477334d30464931346c7a5931554c696947564a59744c71765856762f556b6d6d70395873644249770a576373372b6759704e564d517841646b384d49746c35793552684a71715376472b6a44456a734841743558724c4c74473451646977334e626c393864557072510a3558726175676e4179454e4a586e696d3237507a35412f374e67497a6a54477a4645476f56314f376c4445586b5a553d0a2d2d2d2d2d454e442043455254494649434154452d2d2d2d2d0a"
00:00:01 - Qt Info: Discovered mDNS host: "GERMAN-ROG-2.local."
00:00:01 - Qt Info: Resolved "GERMAN-ROG-2.local." to QHostAddress("192.168.0.125")
00:00:01 - Qt Info: Resolved "GERMAN-ROG-2.local." to QHostAddress("fe80::d8f5:9f96:8bb:4602")
00:00:03 - Qt Info: Processing new PC at "192.168.0.125:47989" from mDNS with IPv6 address "<NULL>"
00:00:03 - Qt Info: Executing request: "http://192.168.0.125:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=f8a951538bff4518bd036827c2b71f19"
00:00:03 - Qt Info: Executing request: "https://192.168.0.125:47984/serverinfo?uniqueid=0123456789ABCDEF&uuid=a3148c694a384bf39bc5f8755131a912"
00:00:03 - Qt Info: Executing request: "http://192.168.0.125:47989/serverinfo?uniqueid=0123456789ABCDEF&uuid=54cf1c411bd045b894e2d9f4bb1e1173"
00:00:05 - Qt Info: Executing request: "http://192.168.0.125:47989/pair?uniqueid=0123456789ABCDEF&uuid=983bacbbb3c64321891cbeeac3a22433&devicename=roth&updateState=1&clientchallenge=394f1714d08a3b1244724c6031da3fa5"
00:00:05 - Qt Info: Executing request: "http://192.168.0.125:47989/pair?uniqueid=0123456789ABCDEF&uuid=fadc77a560884a11a6d53e3a738c8e37&devicename=roth&updateState=1&serverchallengeresp=517a3a98ffd07c5a09c3ea6c4a75706833d7e4f6d9324b4d5d7ab0734b5692d6"
00:00:06 - Qt Info: Executing request: "http://192.168.0.125:47989/pair?uniqueid=0123456789ABCDEF&uuid=357ce467ea5442f1b55488a863b8693d&devicename=roth&updateState=1&clientpairingsecret=6d16e1e786bf237000dc053dd0c6debe42f483aa3269e2b1403def8f370765baf3ac78f27d19d7aefab2fc2abe35345875499e57b8e99ac30a39a2e1f7c2a35de3b27e0e7d20267ae1ad60667889af59191c13b5f49fd1c29d1bcbba22fca6505cb3b9fe0290189ec3869757fa6499b3669c26c393a274effca3d59ae25fc1165919eeb0551236d361af342f1072430e3bb93aa93d19a9c74427e2ffaa7b224dfbd1ea108cf07c3f6220ad6fc4090af3e9c75bda73b3e0f49125c2ac874b78c709eb90dc4cae137a56e3de987b1866f9cb89d089b7f395f33a39db7750bceb5361121b44cbddecc7d9f67e6aef93ead4ef1b18f64268fd02b62ab6dfd2a598ca305a9ddf3258bcc893942da5d9ab8158"
00:00:06 - Qt Info: Executing request: "https://192.168.0.125:47984/pair?uniqueid=0123456789ABCDEF&uuid=a7be5fb65812464ca67ea5548ee397c6&devicename=roth&updateState=1&phrase=pairchallenge"

**Comment by cgutman** [comment] 2022-05-28 18:23
Likely duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30

**Closed by cgutman** 2022-05-28 18:23 UTC
