### ISSUE TITLE
[request] Add hide option to games in list, and interaction gui

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#316] opened 2019-12-23 04:28 UTC
Please add an option to hide/show games in the list of Moonlight, and also add an interaction GUI to ask "Do you want to start streaming" for the game after clicking on it.

**Comment by cgutman** [comment] 2019-12-23 15:31
Duplicate of #255

**Closed by cgutman** 2019-12-23 15:31 UTC
