### ISSUE TITLE
Connect to already running game that was started locally.

### ISSUE THREAD

**Issue by patlefort** [moonlight-stream/moonlight-qt#706] opened 2022-01-09 01:30 UTC
Is it possible to do with nvidia GameStream? If I try to connect, it will fail with an error about the game having been started locally already with code 526. It will fail if I try anything other programs. To connect, I have to close the game on the host first which is simply inconvenient (what if I can't leave the game at that moment?). I know it can happily stream my desktop and start and stop any games if I connect via a placeholder program like notepad. Why is it so hellbent on wanting to start apps itself?

**Comment by jorys-paulin** [comment] 2022-01-09 08:51
Hello, from previous reports on the Discord server, it _seems_ like you need to use TeamViewer or similar to un focus the game, as it _seems_ to be the cause of the error.

**Comment by patlefort** [comment] 2022-01-09 13:28
I've tried that but it still gave the same error. After further testing, I think it prevent connections if a game is running in exclusive fullscreen. Some games will minimize if I unfocus them and then I can connect, but some games don't and won't let me connect regardless. Running the game is windowed or windowed fullscreen mode let me connect anytime.

**Comment by jorys-paulin** [comment] 2022-01-09 14:25
Games running in exclusive fullscreen are considered focused aren't they? I guess you can always go to the desktop, exiting out of the exclusive fullscreen game?

**Comment by patlefort** [comment] 2022-01-09 16:15
The game in particular is Phantasy Star Online 2: NGS. On my setup with multiple screens, if I just click on another window in another screen, the game still appear to be fullscreen. If I alt+tab out of it, it goes in windowed mode. Maybe in the first case, it's quickly changing to fullscreen windowed?

**Comment by cgutman** [comment] 2022-05-30 21:00
The mstsc.exe method is the best way to avoid this issue.

Ultimately, this behavior is a bug in GeForce Experience (which is what's failing with that "already running locally" error), not Moonlight, so I will close this bug as "can't fix"/"not our bug"

**Closed by cgutman** 2022-05-30 21:00 UTC
