### ISSUE TITLE
Raw input and touch don't work well together on Windows

### ISSUE THREAD

**Issue by spv25** [moonlight-stream/moonlight-qt#140] opened 2018-11-28 23:36 UTC
I'm streaming from my Desktop PC to an HP x360 Spectre Pro G1 laptop.

Upon opening mstsc.exe, I can use the touchpad and keyboard just fine, but when it comes to the touch controls on the display, there are some problems. The cursor appears about 4-5cm diagonally away from where my finger/pen tip is, and it seems to randomly click on and off.

If I turn raw mouse input off, while it seems to control a lot better, I can no longer click by touching, and I can only move the cursor from it's present position. For example, if the cursor is in the centre of the screen, and I tap the top left of the display, it will remain stationary. If I swipe down from the top left, the cursor will move from the middle to the bottom right.

**Comment by cgutman** [comment] 2018-11-28 23:46
The raw input issue is a bug in SDL that I'm investigating.

With raw input turned off, that's working as intended. The touchscreen is expected to act like a trackpad and not an absolute pointing device. GameStream doesn't have support for absolute pointing devices natively.

**Comment by cgutman** [comment] 2019-07-03 06:08
I submitted a patch to SDL to fix this: https://bugzilla.libsdl.org/show_bug.cgi?id=4704

**Comment by cgutman** [comment] 2019-07-09 02:12
Fixed upstream with https://hg.libsdl.org/SDL/rev/92e72926b7f5

**Comment by cgutman** [comment] 2019-07-28 19:02
Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/4caa329c36bbd70ba070743f2d3a041d75487a5a

**Closed by cgutman** 2019-07-28 19:02 UTC
Labels: bug
