### ISSUE TITLE
Display Mode "Windowed" is not effective as the selected resolution

### ISSUE THREAD

**Issue by jacky723** [moonlight-stream/moonlight-qt#1289] opened 2024-05-24 15:42 UTC
**Describe the bug**
I am now using steamdeck to install the moonlight client. I selected 4K in the Resolution and FPS under the Basic Settings. And I also selected "Windowed" for the Display mode. However, the streaming output is not 4K, it is somehow lower than 800P.

**Steps to reproduce**
I doubted if this issue is just caused by network speed, but I tried to change the Display mode to Fullscreen and Borderless windowed, they both look aligned to 4K, which means there might be issue with "Windowed" option for the Display mode. 

Would like to know, whether I have solution on this? I really need to use "Windowed" Display mode, as I want to use the screen stretch feature to fix steamdeck 16:10 resolution problem. (ps. I know that I can use dummy hdmi/virtual monitor, but they are really not my preferred use case, I just want to use the stretching feature to keep it simple) Many thanks!

**Comment by cgutman** [comment] 2024-05-27 17:08
Duplicate of #879

The fix is posted in a comment there. You need to set Moonlight's resolution in the Steam settings to use "Native" not "Default" (which scales everything to 1280x800).

**Closed by cgutman** 2024-05-27 17:08 UTC
