### ISSUE TITLE
Support more key combinations to be sent to the GameStream PC

### ISSUE THREAD

**Issue by zeroClearAmerican** [moonlight-stream/moonlight-qt#444] opened 2020-09-17 22:16 UTC
**Is your feature request related to a problem? Please describe.**
Some common key combinations don't seem to work with the [recommended method to stream the full desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop), but other key combinations work, such as CTRL-C.

**Describe the solution you'd like**
All normally-captured key combinations, _besides Moonlight's own combinations and CTRL-ALT-DELETE_, to be captured and sent to the GameStream PC when using mstsc.exe to stream the entire desktop. Maybe even make a "blacklist" of key combinations that are never captured that is editable in the Settings screen.

**Describe alternatives you've considered**
Other alternatives to Moonlight aren't nearly as fast and therefore defeat the purpose. Additionally some key combination functionalities have no other alternative, like ALT-TAB. 

**Additional context**
Encountered this issue first when trying to ALT-TAB between programs on the GameStream PC.
Can also be replicated by attempting to switch virtual desktops on the GameStream PC using the _CTRL-WIN-Left Arrow_ and _CTRL-WIN-Right Arrow_ keyboard shortcuts while the client PC also has more than one virtual desktop active.

**Comment by holcombj** [comment] 2020-09-21 00:29
I'm not a moonlight developer, but I've encountered the same issue.  The bottom line is that Nvidia's server doesn't allow certain key combination to come in.  Here are two [similar](https://github.com/moonlight-stream/moonlight-chrome/issues/436) [issues](https://github.com/moonlight-stream/moonlight-chrome/issues/455) brought up in the moonlight-chrome project, which have the same root cause.

My workaround (specifically for ALT-TAB, but a similar approach could be taken for other blocked keys) is to use [AutoHotKey](https://www.autohotkey.com/) script to trigger similar behavior.

Specifically, to do something similar to ALT-TAB, I use the following script:

> #NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
> ; #Warn  ; Enable warnings to assist with detecting common errors.
> SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
> SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
> F10::
> Send, ^!{Tab}
> ;Send {LAlt down}{Tab}{LAlt up}
> ;return
> 

You then press F10 to cycle between the window you want and press "Enter" when you have cycled to the correct window.  It isn't identical to the normal ALT-TAB functionality, but it has worked well for me.

Hope that helps.

**Comment by cgutman** [comment] 2021-01-13 02:11
Fixed by 76b4922bbe9d7b34d5a492ebe7a5c7a8ebbf52d0

**Closed by cgutman** 2021-01-13 02:11 UTC
Labels: enhancement
