### ISSUE TITLE
Vsync issue

### ISSUE THREAD

**Issue by kjs00333** [moonlight-stream/moonlight-qt#262] opened 2019-08-03 19:25 UTC
Hi all - Got a question / issue.  When connecting to my desktop via moonlight, all works fine but I noticed screen tearing.  The desktop I'm connecting to has a monitor that is a 165hz 4k GSync monitor, and I'm connecting from a laptop with a 60hz screen.  When I enable vsync in the moonlight options, the mouse doesn't work and it gets stuck to the point where I have to reboot my client machine.  Anybody know what I can do to alleviate this?  Do I need to set my host computer to 60hz as well?

I am using the latest version of the moonlight client, the latest nvidia drivers on both machines with updated geforce experience. Nvidia 2080ti on windows 10 latest build.

Thank you

**Comment by cgutman** [comment] 2019-08-03 19:57
This is probably a duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/240

Can you try a recent dev build from here? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/26450350/job/fgr7jl6h8uo0pclx/artifacts

Use the portable version, not the installer (otherwise you will need to uninstall your existing build before installing the dev build).

**Comment by kjs00333** [comment] 2019-08-03 20:12
The dev build has corrected the issue.  Thank you !

**Closed** 2019-08-11 18:36 UTC

**Comment by HoppyBrewno42** [comment] 2024-05-30 18:26
Hi, I was looking for a post like this, but I don't understand the solution. I'm a noob and my TV monitor's Vsync doesn't work well with Moonlight. Care to reexplain a solution?

Thanks,
Brewno
