### ISSUE TITLE
some times hang when capture mouse in linux

### ISSUE THREAD

**Issue by xux1217** [moonlight-stream/moonlight-qt#569] opened 2021-04-14 14:17 UTC
**Describe the bug**
I using my own compile moonlight in Linux.

Some times, when I use "Ctrl-Alt-Shift-Z" to capture mouse, and click other window, the moonlight would be black screen and then stuck in one frame. I must use "pkill -9 moonlight" to exit the client and restart it. 

This is a client problem, because when I restart moonlight, I can continue the previous game.

This problem occurs in all games, and appear randomly. 

When I use software decoding, it's not this problem, but has too large lantency.
This problem has occurs whether vsync on or off and "Frame packing" also.
By Display mode, "Fullscreen" and "Borderless windowed" has this problem, but "windowed" is work normally.

I use the official appimage version also has this problem(link: https://github.com/moonlight-stream/moonlight-qt/releases/download/v3.1.1/Moonlight-3.1.1-x86_64.AppImage).

The official client in other operation system is not this problem(eg: dmg in mac OS).

**My OS version**: Gentoo, kernel version: 5.10.27-gentoo-x86_64
**Nvidia Official driver**: 
NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2 
**FFmpeg version**:  4.3.2
**gnome version**: 3.36.4, use X11
**qmake version**:
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib64
**Moonlight version**: 
00:00:00 - SDL Info (0): Compiled with SDL 2.0.12
00:00:00 - SDL Info (0): Running with SDL 2.0.12
00:00:00 - Qt Info: No translation available for  "en"
Moonlight 3.1.0

I use the official way to compile: https://github.com/moonlight-stream/moonlight-qt#build-setup-steps

the logs is in the attach file:
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/6311504/moonlight.log)

**Comment by cgutman** [comment] 2021-04-15 16:06
I believe this is a duplicate of #434 

It is a bug in the Nvidia proprietary driver as far as I can tell.

**Closed by cgutman** 2021-04-15 16:06 UTC
