### ISSUE TITLE
Numpad key "5" does not work

### ISSUE THREAD

**Issue by GuillaumeCauvet** [moonlight-stream/moonlight-qt#230] opened 2019-05-13 10:22 UTC
Had this issue since I first used Moonlight about 2 months ago.
Tried from two different locations to the same target computer (Full OS re-installed inbetween)

**Comment by estepe** [comment] 2019-05-13 10:51
I've been noticing it for the last couple of months too. Occasionally, after switching between moonlight and other windows applications, numpad 5 seems to be work again.

**Comment by cgutman** [comment] 2019-05-24 15:51
I'm not able to reproduce this locally on Windows 10 19H1 on client and server. Is there some special needed to trigger it?

**Comment by cgutman** [comment] 2019-05-27 05:02
I was able to reproduce it after further testing. It is noticeable when I purposefully get the Num Lock state out of sync with the host and client. If Num Lock is active on the host and not on the client, the 5 key stops working on keyboardtester.com.

This is caused by a bug in SDL that's being tracked upstream - https://bugzilla.libsdl.org/show_bug.cgi?id=4443

**Comment by cgutman** [comment] 2019-06-15 19:51
It will be fixed in SDL 2.0.10

**Comment by estepe** [comment] 2019-06-15 22:00
Great to hear, i'm really looking forward to it! 

Thnx for the update!

**Comment by cgutman** [comment] 2019-07-28 19:02
Fixed by https://github.com/moonlight-stream/moonlight-qt/commit/4caa329c36bbd70ba070743f2d3a041d75487a5a

**Closed by cgutman** 2019-07-28 19:02 UTC
