### ISSUE TITLE
 Moonlight crash when switching audio device - macOS

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [moonlight-stream/moonlight-qt#627] opened 2021-07-23 06:37 UTC
**Description of the bug**
Moonlight crash when switching audio device - macOS

**Steps to reproduce**
1. Stream windows pc on mac ( specifically mstc.exe)
2. Start a movie on windows (haven't checked with streaming service, but local movie crashes).
3. Pause it and connect airpods to the mac.
4. Watch it crash.

**Screenshots**
N/A

**Affected games**
Probably everything that requires audio output. Tested by playing movies locally.

**Other Moonlight clients**
Moonlight MacOS client

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? - No
- If so, which settings have been changed? - NA
- Does the problem still occur after reverting settings back to default? - NA

**Client PC details (please complete the following information)**
 - OS: macOS
 - Moonlight Version: v3.1.3
 - GPU: Radeon Pro 555X 4 GB

**Server PC details (please complete the following information)**
 - OS: Windows 10 Home 20H2
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 461.92
 - Antivirus and firewall software: Windows Firewall

**Moonlight Logs (please attach)**
Crash Log - https://pastebin.com/LPPTY6ZS
Temp Log - https://pastebin.com/DjS0axEb

**Comment by RAJAGOPALAN-GANGADHARAN** [comment] 2021-07-23 06:38
If you guys think this is a valid issue, I'd be willing to get this fixed.

**Comment by cgutman** [comment] 2021-07-23 12:47
Duplicate of #560

This is specific to AirPods.

**Closed by cgutman** 2021-07-23 12:47 UTC
