### ISSUE TITLE
Wake on lan feature in Moonlight takes often very long to send the signal

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#1072] opened 2023-09-21 20:59 UTC
If you have a server configured for WOL and use Moonlight Windows client to wake it up by right click on server and click wake up, it takes sometimes very long until the server wakes up, up to 10 seconds. If you do this with a 3rd party WOL tool, it works instantly.

Please also add a refresh button to the Moonlight gui which scans for servers if you click it.

**Comment by cgutman** [comment] 2023-09-21 22:44
Duplicate of #1037

**Closed by cgutman** 2023-09-21 22:44 UTC
