### ISSUE TITLE
Mouse support on iPad OS 13

### ISSUE THREAD

**Issue by wajubalo** [moonlight-stream/moonlight-qt#266] opened 2019-08-16 08:55 UTC
**Is your feature request related to a problem? Please describe.**
I use the iPad Pro as client to receive a stream of Windows 10 via Moonlight. With mouse support now a feature in iPad OS 13, moonlight also supporting it would be amazing. 

Keyboard + native mouse support would make my iPad Pro practically a powerful Windows laptop (when connected to Moonlight). 

**Describe the solution you'd like**
Enable mouse support on moonlight. The end result would be the ability to stream host PC Windows 10 to an iPad Pro via Moonlight, and then use iPad blue tooth connected mouse to operate the host. 

**Describe alternatives you've considered**
Currently mouse does work, but in the same way dragging your finger across the screen works. Not ideal.

**Comment by cgutman** [comment] 2019-08-16 16:02
This is a duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/369

**Closed by cgutman** 2019-08-16 16:02 UTC
