### ISSUE TITLE
memory leak on minimizing 

### ISSUE THREAD

**Issue by Numerok** [moonlight-stream/moonlight-qt#180] opened 2019-02-18 16:45 UTC
I was playing Dead by daylight with 8.1 client and everything seemed ok but sometimes once maximizing moonlight it appeared tiny in top left corner. Now, with 9.0 and 9.1 clients once i minimize window sometimes (just random) it starting to eat memory like crazy. in task manager there is nothing in processes tab(~300mb while stream is on) but "modified" part of memory starts to overflow (see screenshot of task manager)

**Steps to reproduce**
while playing some time just minimized moonlight and this happened randomly
I was trying to reproduce this with minimizing and maximizing frequently but I did not get any results

**Screenshots**
(alt http://prntscr.com/mmrlf6/direct)
 ![screenshot1](https://image.prntscr.com/image/ViPoxyZtTnSj0tAA7FOYAA.png) 

**Affected games**
Dead by daylight /t mstsc, others not tested, cuz it happens randomly

**Moonlight settings (please complete the following information)**
1366x768 120fps 35mbps
optimizations off
software h264 rendering

**Client PC details (please complete the following information)**
 - OS: windows 10 1709
 - Moonlight Version: 0.9.0-0.9.1
 - Detected GPU: Intel(R) HD Graphics 3000 (8086:116)
 - GPU driver: nvumdshimx.dll 23.21.13.9077

**Server PC details (please complete the following information)**
 - OS: Windows 10 1803
 - Server GPU: "GeForce GTX 960"
 - Server GFE version: "3.16.0.140"
 - Nvidia GPU driver: 418.81

**Moonlight Logs (please attach)**
was lost while force closed with task manager(please return old, procedurally generated log)

**Comment by cgutman** [comment] 2019-02-18 18:34
Are you using Moonlight in windowed mode then minimizing using the minimize button or are you in full-screen and minimizing with Alt+Tab?

Nothing has changed about the logging code since 0.8.1. The log should still be on disk even if you kill Moonlight.

If it happens again, please also get a memory dump of the Moonlight process by right-clicking Moonlight.exe on the Details tab and choosing Create Dump File. You can zip it and upload it somewhere for me to look at.

**Comment by Numerok** [comment] 2019-02-18 19:09
i'm using full-screen mode and minimizing with Alt+Tab. Vsync off

>Nothing has changed about the logging code since 0.8.1.

this is strange than, because i could not find fresh log file after this crash, only with success closing before that
can it be somewhere else besides %TEMP% folder and root folder? because in both locations there is no log file where edit or creation time coincide matches with the time it crashed

>If it happens again, please also get a memory dump of the Moonlight process

i'll try to get memory dump but i'm not promising, cuz my pc hangs once this happens, i even took this screenshot after i closed moonlight and graphs was not updating for a couple of minutes.  it was hard even to close it because even my mouse was lagging, disk overloaded because of swap file and tabs was switching very slow (i was on graphs tab)

**Comment by cgutman** [comment] 2019-02-18 20:30
The issue is fixed by https://github.com/moonlight-stream/moonlight-qt/commit/e5a8b49c93cdd7a320903f41a76482e1fcd733a2. You can can get the fixed build [from here](https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/22465262/job/31kwf46bfai9cut4/artifacts). You will need to do a clean install if you use the normal installer, otherwise you can run the portable installation and delete portable.dat if you want it to pick up your existing settings.

The issue was that an unlimited number of frames can queue waiting for rendering if rendering is blocked for a while. Realistically, this issue only affects the software decoder because hardware decoders are limited by other resource pools (CVPixelBuffers, IDirect3DSurface9s, etc.) before they can fill an appreciable amount of RAM or VRAM. The fix was to limit the number of frames that could be accumulated to some sane amount.

The audio buffer size is probably not your issue. 15 ms is not likely to be human-perceptible. It would need to be [significantly more delayed](http://www.atsc.org/wp-content/uploads/pdf/audio_seminar/12%20-%20JONES%20-%20Audio%20and%20Video%20synchronization-Status.pdf) to be perceptible. If you are noticing it, it is probably delayed far more than 15 ms. I don't notice any perceptible audio delay when testing on my PC. I would suggest you file a separate issue for that with logs or discuss on the Discord server in the #pc-help channel.

**Closed by cgutman** 2019-02-18 20:30 UTC
