### ISSUE TITLE
Xbox Series X Controller stopped working with Moonlight 3.0.0

### ISSUE THREAD

**Issue by btorresgil** [moonlight-stream/moonlight-qt#503] opened 2021-01-19 06:38 UTC
**Describe the bug**
The new [Xbox Series X Controller](https://www.microsoft.com/en-us/p/xbox-wireless-controller/8XN59CRBSQGZ/JBFJ) (aka Xbox Core Controller) does not work in Moonlight 3.0.0 on MacOS. It did work in Moonlight 2.2.0 if launched with the latest `gamecontrollerdb.txt` in the working directory or with the `SDL_GAMECONTROLLERCONFIG` environment variable as shown in the example below.

**Steps to reproduce**

Working in 2.2.0:
1. Connect Xbox Series X Controller to MacOS using Bluetooth
2. Launch Moonlight 2.2.0 from terminal with a gamepad mapping hint: `SDL_GAMECONTROLLERCONFIG="030000005e040000130b000005050000,Xbox Series Controller,a:b0,b:b1,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a5,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a4,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Mac OS X," /Applications/Moonlight.app/Contents/MacOS/Moonlight`
3. Connect to server PC and launch a game, Steam Big Picture, or remote desktop session.
4. Observe that the Xbox Series X controller works

Non-working in 3.0.0:
1. Connect Xbox Series X Controller to MacOS using Bluetooth
2. Launch Moonlight 3.0.0 as normal, or from the terminal using the same command as the 2.2.0 example above (ether way is the same result because 3.0.0 already has this updated mapping, so the environment variable is not necessary.)
3. Connect to server PC and launch a game, Steam Big Picture, or remote desktop session.
4. Observe that controller shows as Xbox 360 controller as expected, but no input from the controller is registered.

**Affected games**
All games and software are affected.

**Other Moonlight clients**
I have not tested Windows or Linux clients. This doesn't yet apply to iOS client as iOS doesn't support this controller yet.

**Moonlight settings**
Moonlight fresh install, no settings changed. The only non-default setting is the `SDL_GAMECONTROLLERCONFIG` environment variable to get the controller to work in Moonlight 2.2.0.

**Client PC details (please complete the following information)**
 - OS: MacOS 10.15.7
 - Moonlight Version: 3.0.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 10.0.19041
 - GeForce Experience version: 3.20.5.83
 - Nvidia GPU driver: 461.09

**Moonlight Logs**

Logs from working 2.2.0:
[Moonlight-2.2.0.log](https://github.com/moonlight-stream/moonlight-qt/files/5834009/Moonlight-2.2.0.log)

Logs from non-working 3.0.0:
[Moonlight-3.0.0.log](https://github.com/moonlight-stream/moonlight-qt/files/5834012/Moonlight-3.0.0.log)

**Additional context**
In the logs attached you can see the controller is detected differently in 3.0.0.

In 2.2.0 logs it is detected as GUID `030000005e040000130b000005050000` with the name `Xbox Series Controller`

In 3.3.0 logs it is detected as GUID `030000005e040000130b000005056800` with the name `*`

When using a simple SDL2 script completely separate from Moonlight such as the one offered [here](https://askubuntu.com/a/368711/321856) to detect the gamepad/joystick, SDL2 identifies the gamepad as GUID `030000005e040000130b000005050000` (just like Moonlight 2.2.0), so this issue doesn't seem caused by SDL2 (at least not the version of SDL2 I'm using).

**Comment by cgutman** [comment] 2021-01-19 14:47
Sounds like it's a regression in SDL 2.0.14+. SDL 2.0.12 which shipped with Moonlight v2.2.0 had no support for the Xbox Series X controller, so it used the generic HID support in the OS. Now that SDL 2.0.14 has support for it, the built-in SDL HID driver will take over the controller to provide extra functionality like rumble. It sounds like the SDL driver isn't working properly.

I don't have a Series X controller, but I did try my Xbox One S controller via Bluetooth (which uses the same driver inside SDL) on my Mac. That worked properly for me so the driver isn't totally hosed at least.

First thing to try is to disable HIDAPI support to use the OS HID support by running Moonlight like:
`SDL_JOYSTICK_HIDAPI=0 /Applications/Moonlight.app/Contents/MacOS/Moonlight`

Also it would be helpful to get the exact firmware revision of your Series X controller. On a Windows 10 PC, download the Xbox Accessories app from the Microsoft Store, plug in your Series X controller via USB to that PC, then open the app and it should tell you what firmware version the controller is running.

It may also offer you a newer firmware. If it does, you can update it if you want and that might fix it, but please make sure to report the old version here so that the SDL folks can figure out which firmware they need to track down to reproduce the issue.

**Comment by btorresgil** [comment] 2021-01-19 16:47
Hi @cgutman , thanks so much for the quick reply.

Your assessment seems spot on. Here are some new observations based on your comments:

- When I tested with a script using SDL alone, outside of Moonlight, and the controller was detected correctly, I was testing on SDL 2.0.12, so if the issue was introduced after that, it would be consistent with what I'm seeing.

- When Moonlight 3.0.0 is started with `SDL_JOYSTICK_HIDAPI=0`, the controller works! The log indicates it is identified as `030000005e040000130b000005050000` which is the same working GUID as Moonlight 2.2.0 and SDL 2.0.12.

- The firmware on the Xbox Series X controller is the current latest: 5.5.2641.0. I had upgraded the firmware before using the controller, so I don't know what the behavior would be on any previous firmware.

This seems to confirm your theory that this is an SDL issue. What should be the next step? Should I open a bug with SDL? Looks like they use [bugzilla](https://bugzilla.libsdl.org), I searched but don't see a related bug there. Or do you have connections with them you would like to address this with? Happy to help any way I can.

Thanks again!

**Comment by btorresgil** [comment] 2021-01-19 17:40
As an additional test, I upgraded my SDL2 to 2.0.14 and ran my joystick detect script separate from Moonlight again. It now detects the controller as GUID `030000005e040000130b000005056800`, which is the same as Moonlight 3.0.0 when it's not working. So this is further confirmation that the issue was introduced in SDL2 at some point after 2.0.12.

**Comment by cgutman** [comment] 2021-01-22 01:32
Yes, it would be ideal if you could submit a bug on their Bugzilla, especially since it's a regression from SDL 2.0.12 to SDL 2.0.14. You could post your joystick detection script there too (and any other instructions required to reproduce the issue).

I would try to help debug it, but I don't have the hardware.

**Comment by abusse** [comment] 2021-01-30 12:29
I think, I have the same issue with a DualShock 4 controller. It stopped working after upgrading 3.0.0. Going back to 2.2.0, everything works again.

**Comment by cgutman** [comment] 2021-01-30 14:28
> I think, I have the same issue with a DualShock 4 controller. It stopped working after upgrading 3.0.0. Going back to 2.2.0, everything works again.

What OS is your Moonlight client running?

**Comment by abusse** [comment] 2021-01-31 15:10
Linux

**Comment by cgutman** [comment] 2021-01-31 16:04
@abusse ok, please file a separate issue for that, since it's different hardware and a different OS. The cause is likely different.

Please include the logs from Moonlight too when trying to stream, like the reporter of this issue did.

**Comment by btorresgil** [comment] 2021-01-31 19:43
I opened [bug 5523](https://bugzilla.libsdl.org/show_bug.cgi?id=5523) on SDL2 for this issue. @cgutman thanks for your support to narrow it down to an SDL problem!

**Comment by cgutman** [comment] 2021-02-05 06:00
This is now fixed in the new SDL prebuilts with https://github.com/moonlight-stream/moonlight-qt/commit/4b9e90ac7287f3575004579ac58b931aac595d44

If you want to try CI build with the fix, you can find one here: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/37622193/job/yesa0f4e90088jwk/artifacts

**Closed by cgutman** 2021-02-05 06:00 UTC
